export interface Officer {
  role: string;
  name: string;
  shortName: string;
}

export interface Student {
  name: string;
  image: string;
}

export interface OtherPhoto {
  title: string;
  image: string;
}

export interface SectionData {
  id: string;
  title: string;
  adviser: {
    name: string;
    image: string;
  };
  cover: {
    classPhoto: string;
  };
  officers: Officer[];
  students: Student[];
  other: OtherPhoto[];
}

export const sections: SectionData[] = [
  {
    id: '411G',
    title: '411-G',
    adviser: { name: 'Margarita S. Cruz', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Ma. Carla F. Carneo', shortName: 'Carla Carneo' },
      { role: 'Vice-President', name: 'Lili-jane T. Ramos', shortName: 'Lili-jane Ramos' },
      { role: 'Secretary', name: 'Paz Genevieve J. Abay', shortName: 'Paz Genevieve Abay' },
      { role: 'Treasurer', name: 'Herminia F. Gabutina', shortName: 'Herminia Gabutina' },
      { role: 'P.R.O.', name: 'Janette S. Miranda', shortName: 'Janette Miranda' },
      { role: 'Sgt. at Arms', name: 'Rachel C. Consumido', shortName: 'Rachel Consumido' }
    ],
    students: [
      { name: 'Paz Genevieve J. Abay', image: 'students/paz-abay.webp' },
      { name: 'Pinky Rosemarie C. Abaya', image: 'students/pinky-abaya.webp' },
      { name: 'Michele F. Abellanosa', image: 'students/michele-abellanosa.webp' },
      { name: 'Salvacion Genalin P. Alday', image: 'students/salvacion-alday.webp' },
      { name: 'Zoraida Grace L. Avendano', image: 'students/zoraida-avendano.webp' },
      { name: 'Ma. Luisa R. Banzon', image: 'students/luisa-banzon.webp' },
      { name: 'Ma. Floriam N. Bay', image: 'students/floriam-bay.webp' },
      { name: 'Sheila M. Bernardo', image: 'students/sheila-bernardo.webp' },
      { name: 'Jennifer A. Cabrera', image: 'students/jennifer-cabrera.webp' },
      { name: 'Grace Celia C. Capuz', image: 'students/grace-capuz.webp' },
      { name: 'Ma. Carla F. Carneo', image: 'students/carla-carneo.webp' },
      { name: 'Babe-Ruth R. Centeno', image: 'students/baberuth-centeno.webp' },
      { name: 'Rachel C. Consumido', image: 'students/rachel-consumido.webp' },
      { name: 'Catherine C. Cornista', image: 'students/catherine-cornista.webp' },
      { name: 'Marie Celeste S. Cortes', image: 'students/marie-cortes.webp' },
      { name: 'Bernardita J. Cruz', image: 'students/bernardita-cruz.webp' },
      { name: 'Jocelyn R. Cuevas', image: 'students/jocelyn-cuevas.webp' },
      { name: 'Grace M. Cumpas', image: 'students/grace-cumpas.webp' },
      { name: 'Ma. Cecilia G. Duka', image: 'students/cecilia-duka.webp' },
      { name: 'Ma. Fatima S. Erasmo', image: 'students/fatima-erasmo.webp' },
      { name: 'Flerida S. Fabia', image: 'students/flerida-fabia.webp' },
      { name: 'Roselle B. Fajardo', image: 'students/roselle-fajardo.webp' },
      { name: 'Marissa M. Fournier', image: 'students/marissa-fournier.webp' },
      { name: 'Veronica M. Ga', image: 'students/veronica-ga.webp' },
      { name: 'Anna Michelle N. Gabriana', image: 'students/anna-gabriana.webp' },
      { name: 'Herminia F. Gabutina', image: 'students/herminia-gabutina.webp' },
      { name: 'Mae H. Gajo', image: 'students/mae-gajo.webp' },
      { name: 'Ma. Carla C. Garcia', image: 'students/carla-garcia.webp' },
      { name: 'Rodelia N. Garcia', image: 'students/rodelia-garcia.webp' },
      { name: 'Marie Christine Suzanne V. Garduque', image: 'students/marie-garduque.webp' },
      { name: 'Jennifer De Vera Gloda', image: 'students/jennifer-gloda.webp' },
      { name: 'Memia-lina A. Joven', image: 'students/memialina-joven.webp' },
      { name: 'Ma. Carla De Guzman Laxa', image: 'students/carla-laxa.webp' },
      { name: 'Ma. Racel P. Marcelo', image: 'students/racel-marcelo.webp' },
      { name: 'Madonna C. Martin', image: 'students/madonna-martin.webp' },
      { name: 'Ma. Araceli J. Masaoy', image: 'students/araceli-masaoy.webp' },
      { name: 'Stephanie Magna J. Medina', image: 'students/stephanie-medina.webp' },
      { name: 'Janette S. Miranda', image: 'students/janette-miranda.webp' },
      { name: 'Maida P. Molina', image: 'students/maida-molina.webp' },
      { name: 'Marychilles S. Moncerate', image: 'students/marychilles-moncerate.webp' },
      { name: 'Jennifer J. Monreal', image: 'students/jennifer-monreal.webp' },
      { name: 'Joan O. Montenegro', image: 'students/joan-montenegro.webp' },
      { name: 'Mary Grace C. Peñaflor', image: 'students/mary-penaflor.webp' },
      { name: 'Lili-jane T. Ramos', image: 'students/lilijane-ramos.webp' },
      { name: 'Ma. Theresa Del Rosario', image: 'students/theresa-delrosario.webp' },
      { name: 'Ma. Irene J. Samaniego', image: 'students/irene-samaniego.webp' },
      { name: 'Daisy M. Sandiko', image: 'students/daisy-sandiko.webp' },
      { name: 'Consolacion A. Testa', image: 'students/consolacion-testa.webp' },
      { name: 'Bernadette A. Villamin', image: 'students/bernadette-villamin.webp' },
      { name: 'Melissa L. Yatco', image: 'students/melissa-yatco.webp' },
      { name: 'Jocelyn G. Zabala', image: 'students/jocelyn-zabala.webp' },
      { name: 'Gina A. Zamuco', image: 'students/gina-zamuco.webp' },
      { name: 'Nancy U. Zapata', image: 'students/nancy-zapata.webp' }
    ],
    other: [
      { title: 'All for one, one for all!', image: 'other/classroom.webp' },
    ]
  },
  {
    id: '411B',
    title: '411-B',
    adviser: { name: 'Ermelina T. Vitug', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Arnold V. Sudario', shortName: 'Arnold Sudario' },
      { role: 'Vice-President', name: 'Ian L. Parong', shortName: 'Ian Parong' },
      { role: 'Secretary', name: 'Alexander R. De Leon', shortName: 'Alexander De Leon' },
      { role: 'Treasurer', name: 'Engelbert L. Sepuesca', shortName: 'Engelbert Sepuesca' },
      { role: 'P.R.O.', name: 'Lorenzo S. C. Gonzales', shortName: 'Lorenzo Gonzales' },
      { role: 'Sgt. at Arms', name: 'Eldrige F. Pineda', shortName: 'Eldrige Pineda' }
    ],
    students: [
      { name: 'Jay E. Bailon', image: 'students/jay-bailon.webp' },
      { name: 'Jeffrey T. Balatbat', image: 'students/jeffrey-balatbat.webp' },
      { name: 'Antonio B. Baranda Jr.', image: 'students/antonio-baranda.webp' },
      { name: 'Modesto C. Bermudez Jr.', image: 'students/modesto-bermudez.webp' },
      { name: 'Jerry James B. Bunagan', image: 'students/jerry-bunagan.webp' },
      { name: 'Primo A. Canuela', image: 'students/primo-canuela.webp' },
      { name: 'Joselito R. Capulong', image: 'students/joselito-capulong.webp' },
      { name: 'Jonathan L. Cordon', image: 'students/jonathan-cordon.webp' },
      { name: 'Reonel T. Costales', image: 'students/reonel-costales.webp' },
      { name: 'Aaron M. Decangchon', image: 'students/aaron-decangchon.webp' },
      { name: 'Edgar M. Elamparo I', image: 'students/edgar-elamparo.webp' },
      { name: 'Oliver S. Enriquez', image: 'students/oliver-enriquez.webp' },
      { name: 'Dennis L. Esquejo', image: 'students/dennis-esquejo.webp' },
      { name: 'Allen S. Evaristo', image: 'students/allen-evaristo.webp' },
      { name: 'Joselito G. Florendo', image: 'students/joselito-florendo.webp' },
      { name: 'Arnold B. Gandia', image: 'students/arnold-gandia.webp' },
      { name: 'Gracielo G. Gano', image: 'students/gracielo-gano.webp' },
      { name: 'Jose Mari Romelito L. Garcia', image: 'students/jose-garcia.webp' },
      { name: 'Julius Paul A. Gerrardo', image: 'students/julius-gerrardo.webp' },
      { name: 'Jimmy T. Go', image: 'students/jimmy-go.webp' },
      { name: 'Robertson G. Gonzales', image: 'students/robertson-gonzales.webp' },
      { name: 'Lorenzo S. C. Gonzales', image: 'students/lorenzo-gonzales.webp' },
      { name: 'Ronald L. Hernandez', image: 'students/ronald-hernandez.webp' },
      { name: 'Henry Felix E. Herrera', image: 'students/henry-herrera.webp' },
      { name: 'Joie P. Illescas', image: 'students/joie-illescas.webp' },
      { name: 'Emmanuel R. Kasilag', image: 'students/emmanuel-kasilag.webp' },
      { name: 'Abner U. De Leon', image: 'students/abner-deleon.webp' },
      { name: 'Alexander R. De Leon', image: 'students/alexander-deleon.webp' },
      { name: 'Gregorio D. Lugapo Jr.', image: 'students/gregorio-lugapo.webp' },
      { name: 'Raoul C. Marasigan', image: 'students/raoul-marasigan.webp' },
      { name: 'Richard A. Merino', image: 'students/richard-merino.webp' },
      { name: 'Sonny T. Oliva', image: 'students/sonny-oliva.webp' },
      { name: 'Franklyn G. Panopio', image: 'students/franklyn-panopio.webp' },
      { name: 'Ian L. Parong', image: 'students/ian-parong.webp' },
      { name: 'Romeo C. Pe Benito Jr.', image: 'students/romeo-benito.webp' },
      { name: 'Eldrige F. Pineda', image: 'students/eldrige-pineda.webp' },
      { name: 'John P. Querol', image: 'students/john-querol.webp' },
      { name: 'Romeo L. Quilatan Jr.', image: 'students/romeo-quilatan.webp' },
      { name: 'Claudio Roman T. Rapadas', image: 'students/claudio-rapadas.webp' },
      { name: 'Larry C. Sagum', image: 'students/larry-sagum.webp' },
      { name: 'Enrico S. D. San Diego', image: 'students/enrico-sandiego.webp' },
      { name: 'Michael John A. Sarsa', image: 'students/michael-sarsa.webp' },
      { name: 'Engelbert L. Sepuesca', image: 'students/engelbert-sepuesca.webp' },
      { name: 'Danilo L. Siapuatco', image: 'students/danilo-siapuatco.webp' },
      { name: 'Rosauro F. Suarez', image: 'students/rosauro-suarez.webp' },
      { name: 'Arnold V. Sudario', image: 'students/arnold-sudario.webp' },
      { name: 'Gilbert R. Sumague', image: 'students/gilbert-sumague.webp' },
      { name: 'Manuel O. Tan', image: 'students/manuel-tan.webp' },
      { name: 'Dennis Jay D. Tiongco', image: 'students/dennis-tiongco.webp' },
      { name: 'Richard C. Torres', image: 'students/richard-torres.webp' },
      { name: 'Marcelino S. Tuano', image: 'students/marcelino-tuano.webp' },
      { name: 'Ronald Allan E. Tuazon', image: 'students/ronald-tuazon.webp' },
      { name: 'Lonar Anthony M. Umadhay', image: 'students/lonar-umadhay.webp' },
      { name: 'Rolando P. Verzosa', image: 'students/rolando-verzosa.webp' }
    ],
    other: [
      { title: 'Whackos!', image: 'other/classroom.webp' },
    ]
  },    
  {
    id: '421G',
    title: '421-G',
    adviser: { name: 'Norina Gapasin', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Angie M. Arguna', shortName: 'Angie Arguna' },
      { role: 'Vice-President', name: 'Ma. Cecilia A. Nalagan', shortName: 'Cecilia Nalagan' },
      { role: 'Secretary', name: 'Marie Charlyn O. Exaltado', shortName: 'Marie Charlyn Exaltado' },
      { role: 'Treasurer', name: 'Vivian S. De Guzman', shortName: 'Vivian De Guzman' },
      { role: 'P.R.O.', name: 'Gladys R. Guitan', shortName: 'Gladys Guitan' },
      { role: 'Sgt. at Arms', name: 'Heidi S. Palaca', shortName: 'Heidi Palaca' }
    ],
    students: [
      { name: 'Grace Ann O. Alano', image: 'students/grace-alano.webp' },
      { name: 'Noemi Ruth G. Aldez', image: 'students/noemi-aldez.webp' },
      { name: 'Andrea Gladys Paz P. Aquino', image: 'students/andrea-aquino.webp' },
      { name: 'Angie M. Arguna', image: 'students/angie-arguna.webp' },
      { name: 'Leilani D. Aspeli', image: 'students/leilani-aspeli.webp' },
      { name: 'Myrna F. Atienza', image: 'students/myrna-atienza.webp' },
      { name: 'Elayda Clara Marie T. Beltran', image: 'students/elayda-beltran.webp' },
      { name: 'Florence F. Buerano', image: 'students/florence-buerano.webp' },
      { name: 'Carmela O. Castro', image: 'students/carmela-castro.webp' },
      { name: 'Shirin Marie N. Elio', image: 'students/shirin-elio.webp' },
      { name: 'Ma. Teresita M. Esguerra', image: 'students/teresita-esguerra.webp' },
      { name: 'Cecile N. Espocia', image: 'students/cecile-espocia.webp' },
      { name: 'Marie Charlyn O. Exaltado', image: 'students/marie-exaltado.webp' },
      { name: 'Ressie R. Framil', image: 'students/ressie-framil.webp' },
      { name: 'Vilma T. Gatchalian', image: 'students/vilma-gatchalian.webp' },
      { name: 'Gladys R. Guitan', image: 'students/gladys-guitan.webp' },
      { name: 'Vivian S. De Guzman', image: 'students/vivian-deguzman.webp' },
      { name: 'Ma. Larissa M. Halili', image: 'students/larissa-halili.webp' },
      { name: 'Ma. Cecilia V. Interior', image: 'students/cecilia-interior.webp' },
      { name: 'Ma. Rosario I. Jimenez', image: 'students/rosario-jimenez.webp' },
      { name: 'Katherine T. Justiniano', image: 'students/katherine-justiniano.webp' },
      { name: 'Jolianne Q. Lan', image: 'students/jolianne-lan.webp' },
      { name: 'Candice Twinkle S. Laureta', image: 'students/candice-laureta.webp' },
      { name: 'Josephine P. Linsangan', image: 'students/josephine-linsangan.webp' },
      { name: 'Ma. Viviane P. Magno', image: 'students/viviane-magno.webp' },
      { name: 'Noemi B. Misicampo Jra.', image: 'students/noemi-misicampo.webp' },
      { name: 'Regina Ma. Auxiliadora Mendigoria', image: 'students/regina-mendigoria.webp' },
      { name: 'Naomi G. Milay', image: 'students/naomi-milay.webp' },
      { name: 'Ma. Cecilia A. Nalagan', image: 'students/cecilia-nalagan.webp' },
      { name: 'Ezelyn L. Navarro', image: 'students/ezelyn-navarro.webp' },
      { name: 'Rosalinda G. Ong', image: 'students/rosalinda-ong.webp' },
      { name: 'Ma. Alicia F. Paggabao', image: 'students/alicia-paggabao.webp' },
      { name: 'Heidi S. Palaca', image: 'students/heidi-palaca.webp' },
      { name: 'Connie H. Paris', image: 'students/connie-paris.webp' },
      { name: 'Rowena V. Perez', image: 'students/rowena-perez.webp' },
      { name: 'Mary Ann M. Quilala', image: 'students/maryann-quilala.webp' },
      { name: 'Ma. Pacita B. Rivera', image: 'students/pacita-rivera.webp' },
      { name: 'Nancy Grace A. Robles', image: 'students/nancy-robles.webp' },
      { name: 'Violeta A. San Juan', image: 'students/violeta-sanjuan.webp' },
      { name: 'Ma. Cristina F. Santos', image: 'students/cristina-santos.webp' },
      { name: 'Aimee B. Sarmiento', image: 'students/aimee-sarmiento.webp' },
      { name: 'Ma. Cecilia M. Soller', image: 'students/cecilia-soller.webp' },
      { name: 'Kathrina V. Suarez', image: 'students/kathrina-suarez.webp' },
      { name: 'Mitus L. Sumcad', image: 'students/mitus-sumcad.webp' },
      { name: 'Ma. Virginia G. Tigno', image: 'students/virginia-tigno.webp' },
      { name: 'Shirley G. Tismo', image: 'students/shirley-tismo.webp' },
      { name: 'Rachel M. Tolosa', image: 'students/rachel-tolosa.webp' },
      { name: 'Purificacion N. Tongol', image: 'students/purificacion-tongol.webp' },
      { name: 'Veronica C. Umali', image: 'students/veronica-umali.webp' },
      { name: 'Marites B. Uy', image: 'students/marites-uy.webp' },
      { name: 'Mariechit Gloria S. De Vera', image: 'students/mariechit-devera.webp' },
      { name: 'Marilou S. De Vera', image: 'students/marilou-devera.webp' },
      { name: 'Shirley C. Yu', image: 'students/shirley-yu.webp' }
    ],
    other: [
      { title: 'Mga pa-cute', image: 'other/classroom.webp' },
    ]
  },
  {
    id: '421B',
    title: '421-B',
    adviser: { name: 'Cipriana V. Yu', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'John Ulysses D. Abu', shortName: 'John Abu' },
      { role: 'Vice-President', name: 'Lyndon B. Denia', shortName: 'Lyndon Denia' },
      { role: 'Secretary', name: 'Ferdinand C. Bundang', shortName: 'Ferdinand Bundang' },
      { role: 'Treasurer', name: 'Augusto B. Cruz Jr.', shortName: 'Augusto Cruz Jr.' },
      { role: 'P.R.O.', name: 'Reynaldo C. Idano', shortName: 'Reynaldo Idano' },
      { role: 'Sgt. at Arms', name: 'Neil C. Tan', shortName: 'Neil Tan' }
    ],
    students: [
      { name: 'John Ulysses D. Abu', image: 'students/john-abu.webp' },
      { name: 'Edgardo A. Agbada', image: 'students/edgardo-agbada.webp' },
      { name: 'Jose Ma. G. Alarilla', image: 'students/jose-alarilla.webp' },
      { name: 'Enrique G. Armentia', image: 'students/enrique-armentia.webp' },
      { name: 'William A. Asuncion Jr.', image: 'students/william-asuncion.webp' },
      { name: 'Raymond P. Azul', image: 'students/raymond-azul.webp' },
      { name: 'Robert B. Belleza', image: 'students/robert-belleza.webp' },
      { name: 'Gary Stephen S. Briones', image: 'students/gary-briones.webp' },
      { name: 'Ruben F. Bukas Jr.', image: 'students/ruben-bukas.webp' },
      { name: 'Ferdinand C. Bundang', image: 'students/ferdinand-bundang.webp' },
      { name: 'Reynaldo C. Caladiao', image: 'students/reynaldo-caladiao.webp' },
      { name: 'Ariel C. de Castro', image: 'students/ariel-decastro.webp' },
      { name: 'Kenneth Lee G. de Castro', image: 'students/kenneth-decastro.webp' },
      { name: 'Jeremy C. Chu', image: 'students/jeremy-chu.webp' },
      { name: 'Renante C. Cortez', image: 'students/renante-cortez.webp' },
      { name: 'Hector P. Crisostomo VI', image: 'students/hector-crisostomo.webp' },
      { name: 'Augusto B. Cruz Jr.', image: 'students/augusto-cruz.webp' },
      { name: 'Jesus Romano S. Datu', image: 'students/jesus-datu.webp' },
      { name: 'Lyndon B. Denia', image: 'students/lyndon-denia.webp' },
      { name: 'Ronald Reagan S. Domingo', image: 'students/ronald-domingo.webp' },
      { name: 'John Kerwin G. Du', image: 'students/john-du.webp' },
      { name: 'Henry D. Dumaoal', image: 'students/henry-dumaoal.webp' },
      { name: 'Jericho G. Estrella', image: 'students/jericho-estrella.webp' },
      { name: 'Dennis B. Hatoc', image: 'students/dennis-hatoc.webp' },
      { name: 'Enrique R. Hipolito', image: 'students/enrique-hipolito.webp' },
      { name: 'Reynaldo C. Idano', image: 'students/reynaldo-idano.webp' },
      { name: 'Jonathan C. Javier', image: 'students/jonathan-javier.webp' },
      { name: 'Ronald C. Jimenez', image: 'students/ronald-jimenez.webp' },
      { name: 'Amor P. Lauro', image: 'students/amor-lauro.webp' },
      { name: 'Paul Anthony P. Mandal', image: 'students/paul-mandal.webp' },
      { name: 'Peter P. Mandal', image: 'students/peter-mandal.webp' },
      { name: 'Ronaldo O. Marano', image: 'students/ronaldo-marano.webp' },
      { name: 'John Paul T. Marbella', image: 'students/john-marbella.webp' },
      { name: 'Ace Sterling R. Medina', image: 'students/ace-medina.webp' },
      { name: 'Michael Conrad D. Mendoza', image: 'students/michael-mendoza.webp' },
      { name: 'Julius Pichito T. Minas', image: 'students/julius-minas.webp' },
      { name: 'Stephen Thomas S. Misa', image: 'students/stephen-misa.webp' },
      { name: 'Renato K. Mitra Jr.', image: 'students/renato-mitra.webp' },
      { name: 'Raymond I. Nano', image: 'students/raymond-nano.webp' },
      { name: 'Jesus O. Ocasla', image: 'students/jesus-ocasla.webp' },
      { name: 'Earl R. Perez', image: 'students/earl-perez.webp' },
      { name: 'Maximino S. Picio III', image: 'students/maximino-picio.webp' },
      { name: 'James S. Plaza', image: 'students/james-plaza.webp' },
      { name: 'Rudyard Michael A. Ranjo', image: 'students/rudyard-ranjo.webp' },
      { name: 'Gilbert G. Robles', image: 'students/gilbert-robles.webp' },
      { name: 'Marianito R. Rodrigo', image: 'students/marianito-rodrigo.webp' },
      { name: 'Dennis J. Rotairo', image: 'students/dennis-rotairo.webp' },
      { name: 'Melanio G. Rubio Jr.', image: 'students/melanio-rubio.webp' },
      { name: 'Neil C. Tan', image: 'students/neil-tan.webp' },
      { name: 'Arnold B. Teodoro', image: 'students/arnold-teodoro.webp' },
      { name: 'Randy G. Venezuela', image: 'students/randy-venezuela.webp' },
      { name: 'Anthony Allan D. Villanueva', image: 'students/anthony-villanueva.webp' },
      { name: 'Carlos C. Villarias Jr.', image: 'students/carlos-villarias.webp' }
    ],
    other: [
      { title: 'Nerd paradise', image: 'other/classroom.webp' }
    ]
  },
 {
    id: '412G',
    title: '412-G',
    adviser: { name: 'Corazon R. Gonzales', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Ma. Rachel A. Noble', shortName: 'Rachel Noble' },
      { role: 'Vice-President', name: 'Joanne Claudine E. Tavera', shortName: 'Joanna Tavera' },
      { role: 'Secretary', name: 'Rachel B. Benigno', shortName: 'Rachel Benigno' },
      { role: 'Treasurer', name: 'Cynthia Celeste D. Feliciano', shortName: 'Cynthia Feliciano' },
      { role: 'P.R.O.', name: 'Tricia C. Pariño', shortName: 'Tricia Pariño' },
      { role: 'Sgt. at Arms', name: 'Gloria L. Axibal', shortName: 'Gloria Axibal' }
    ],
    students: [
      { name: 'Maila B. Albania', image: 'students/maila-albania.webp' },
      { name: 'Maria Lara A. Antonio', image: 'students/maria-antonio.webp' },
      { name: 'Eleanor N. Aquino', image: 'students/eleanor-aquino.webp' },
      { name: 'Grace T. Avancena', image: 'students/grace-avancena.webp' },
      { name: 'Gloria L. Axibal', image: 'students/gloria-axibal.webp' },
      { name: 'Rhea Theresa C. Bautista', image: 'students/rhea-bautista.webp' },
      { name: 'Rachel B. Benigno', image: 'students/rachel-benigno.webp' },
      { name: 'Roxanne Angela Q. Borlongan', image: 'students/roxanne-borlongan.webp' },
      { name: 'Deanna C. Cabading', image: 'students/deanna-cabading.webp' },
      { name: 'Ma. Paz Elnora R. Cabatbat', image: 'students/paz-cabatbat.webp' },
      { name: 'Vidaliza S. Canapi', image: 'students/vidaliza-canapi.webp' },
      { name: 'Donabel E. Capitulo', image: 'students/donabel-capitulo.webp' },
      { name: 'Ann Margrette P. Cruz', image: 'students/ann-cruz.webp' },
      { name: 'Emmalou G. Donato', image: 'students/emmalou-donato.webp' },
      { name: 'Ma. Lilaine L. Factoran', image: 'students/lilaine-factoran.webp' },
      { name: 'Cynthia Celeste D. Feliciano', image: 'students/cynthia-feliciano.webp' },
      { name: 'Ma. Aileen S. Gallego', image: 'students/aileen-gallego.webp' },
      { name: 'Ma. Carmelita M. Galvez', image: 'students/carmelita-galvez.webp' },
      { name: 'Remia G. Gamad', image: 'students/remia-gamad.webp' },
      { name: 'Precious C. Halili', image: 'students/precious-halili.webp' },
      { name: 'Jeannette P. Janani', image: 'students/jeannette-janani.webp' },
      { name: 'Gilda Ma. Paz R. Kamus', image: 'students/gilda-kamus.webp' },
      { name: 'Lucrecia Cecilia C. Kasilag', image: 'students/lucrecia-kasilag.webp' },
      { name: 'Janice D. De Leon', image: 'students/janice-deleon.webp' },
      { name: 'Eleanor Katrina M. Leyga', image: 'students/eleanor-leyga.webp' },
      { name: 'Agatha B. Limjoco', image: 'students/agatha-limjoco.webp' },
      { name: 'Mary Shella R. Lofranco', image: 'students/mary-lofranco.webp' },
      { name: 'Annette B. Magno', image: 'students/annette-magno.webp' },
      { name: 'Cristina S. Malangen', image: 'students/cristina-malangen.webp' },
      { name: 'Jannet A. Marino', image: 'students/jannet-marino.webp' },
      { name: 'Patricia Lyn V. Monasterial', image: 'students/patricia-monasterial.webp' },
      { name: 'Anna Merced G. Montana', image: 'students/anna-montana.webp' },
      { name: 'Ma. Suzette A. Ner', image: 'students/suzette-ner.webp' },
      { name: 'Ma. Rachel A. Noble', image: 'students/rachel-noble.webp' },
      { name: 'Tricia C. Parino', image: 'students/tricia-parino.webp' },
      { name: 'Ma. Margarita C. Platon', image: 'students/margarita-platon.webp' },
      { name: 'Rosemarie E. Pulido', image: 'students/rosemarie-pulido.webp' },
      { name: 'Lydda Ludim V. Ragasa', image: 'students/lydda-ragasa.webp' },
      { name: 'Ethel C. Ramones', image: 'students/ethel-ramones.webp' },
      { name: 'Gloria Febe C. Reyes', image: 'students/gloria-reyes.webp' },
      { name: 'Ma. Victoria L. Reyes', image: 'students/victoria-reyes.webp' },
      { name: 'Sheila C. Rillon', image: 'students/sheila-rillon.webp' },
      { name: 'Rosellie D. Rudas', image: 'students/rosellie-rudas.webp' },
      { name: 'Maridel Agnes J. Saldana', image: 'students/maridel-saldana.webp' },
      { name: 'Melissa T. Samaniego', image: 'students/melissa-samaniego.webp' },
      { name: 'Dahlia S. Santos', image: 'students/dahlia-santos.webp' },
      { name: 'Suzanne Claudia S. Santos', image: 'students/suzanne-santos.webp' },
      { name: 'Lana H. Simbulan', image: 'students/lana-simbulan.webp' },
      { name: 'Jermilyn S. Soria', image: 'students/jermilyn-soria.webp' },
      { name: 'Marie Antoinette S. Sto. Domingo', image: 'students/marie-stodomingo.webp' },
      { name: 'Karen F. Tacderas', image: 'students/karen-tacderas.webp' },
      { name: 'Joanne Claudine E. Tavera', image: 'students/joanne-tavera.webp' },
      { name: 'Crishel T. Viste', image: 'students/crishel-viste.webp' },
      { name: 'Rosario Y. Yanga', image: 'students/rosario-yanga.webp' },
    ],
    other: [
      { title: 'Pretty faces?', image: 'other/classroom.webp' },
    ]
  },  
  {
    id: '412B',
    title: '412-B',
    adviser: { name: 'Isabelita Viray', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Vincent Mitch R. Velez', shortName: 'Vincent Velez' },
      { role: 'Vice-President', name: 'Marc Anthony G. Constantino', shortName: 'Marc Constantino' },
      { role: 'Secretary', name: 'Carlito L. Hernandez Jr.', shortName: 'Carlito Hernandez' },
      { role: 'Treasurer', name: 'Paul Andrew B. Parial', shortName: 'Paul Parial' },
      { role: 'P.R.O.', name: 'Fredericko S. Tankeko', shortName: 'Fredericko Tankeko' },
      { role: 'Sgt. at Arms', name: 'Arvin R. Figues', shortName: 'Arvin Figues' }
    ],
    students: [
      { name: 'Allan Christopher S. Agati', image: 'students/allan-agati.webp' },
      { name: 'Joseph Almario Q. Aguas', image: 'students/joseph-aguas.webp' },
      { name: 'Regan Z. Arcega', image: 'students/regan-arcega.webp' },
      { name: 'Chito G. Arevalo', image: 'students/chito-arevalo.webp' },
      { name: 'Carmelo Q. Aribon', image: 'students/carmelo-aribon.webp' },
      { name: 'Efren B. Baniqued', image: 'students/efren-baniqued.webp' },
      { name: 'Joselito L. Basilio', image: 'students/joselito-basilio.webp' },
      { name: 'Benjamin T. Bautista', image: 'students/benjamin-bautista.webp' },
      { name: 'Engelbert M. Bello', image: 'students/engelbert-bello.webp' },
      { name: 'Reginald G. Bulaon', image: 'students/reginald-bulaon.webp' },
      { name: 'Julius B. Capucao', image: 'students/julius-capucao.webp' },
      { name: 'Angelo A. Chua', image: 'students/angelo-chua.webp' },
      { name: 'Zabdiel E. Coloma', image: 'students/zabdiel-coloma.webp' },
      { name: 'Marc Anthony G. Constantino', image: 'students/marc-constantino.webp' },
      { name: 'Christopher D. Capuyoc', image: 'students/christopher-capuyoc.webp' },
      { name: 'Elmer G. Dela Cruz', image: 'students/elmer-delacruz.webp' },
      { name: 'Dennis G. Dayrit', image: 'students/dennis-dayrit.webp' },
      { name: 'Ryan Nolan M. Delfina', image: 'students/ryan-delfina.webp' },
      { name: 'Joel S. Delgado', image: 'students/joel-delgado.webp' },
      { name: 'Leopoldo M. Diaz III', image: 'students/leopoldo-diaz.webp' },
      { name: 'Joel R. Domingo', image: 'students/joel-domingo.webp' },
      { name: 'Jonas Joseppe I. Esperanza', image: 'students/jonas-esperanza.webp' },
      { name: 'Hess M. Espinas', image: 'students/hess-espinas.webp' },
      { name: 'Arvin R. Figues', image: 'students/arvin-figues.webp' },
      { name: 'Jon Anthony G. Gador', image: 'students/jon-gador.webp' },
      { name: 'Israel Ma. E. Gonzalez', image: 'students/israel-gonzalez.webp' },
      { name: 'Noriel Paul B. Gonzalez', image: 'students/noriel-gonzalez.webp' },
      { name: 'Carlito L. Hernandez Jr.', image: 'students/carlito-hernandez.webp' },
      { name: 'Mario Luis B. Hernandez', image: 'students/mario-hernandez.webp' },
      { name: 'Thaddeus Virgilio P. Jamias', image: 'students/thaddeus-jamias.webp' },
      { name: 'Danielito D. Jimenez', image: 'students/danielito-jimenez.webp' },
      { name: 'Michael Martin T. Lagman', image: 'students/michael-lagman.webp' },
      { name: 'Mor O. Lim', image: 'students/mor-lim.webp' },
      { name: 'Vicente Rodel M. Manalang', image: 'students/vicente-manalang.webp' },
      { name: 'Alvin F. Mangona', image: 'students/alvin-mangona.webp' },
      { name: 'Edgardo M. Mapugay', image: 'students/edgardo-mapugay.webp' },
      { name: 'Reynaldo A. Mendoza', image: 'students/reynaldo-mendoza.webp' },
      { name: 'Victor F. Mendoza', image: 'students/victor-mendoza.webp' },
      { name: 'Phillip Martin M. Molines', image: 'students/phillip-molines.webp' },
      { name: 'Axzel H. Del Moro', image: 'students/axzel-delmoro.webp' },
      { name: 'Gerard Raymond C. Ona', image: 'students/gerard-ona.webp' },
      { name: 'Patrick C. Paguia', image: 'students/patrick-paguia.webp' },
      { name: 'Paul Andrew B. Parial', image: 'students/paul-parial.webp' },
      { name: 'Ramon Cristino Z. San Jose', image: 'students/ramon-sanjose.webp' },
      { name: 'Rodney V. Singzon', image: 'students/rodney-singzon.webp' },
      { name: 'Danilo Jose T. Suarez', image: 'students/danilo-suarez.webp' },
      { name: 'Jonathan G. Sumaway', image: 'students/jonathan-sumaway.webp' },
      { name: 'Fredericko S. Tankeko', image: 'students/fredericko-tankeko.webp' },
      { name: 'John Henry E. Tavera', image: 'students/john-tavera.webp' },
      { name: 'Bernard T. Tiongson', image: 'students/bernard-tiongson.webp' },
      { name: 'Ranilo V. Untivero', image: 'students/ranilo-untivero.webp' },
      { name: 'Rommel G. Valencia', image: 'students/rommel-valencia.webp' },
      { name: 'Vincent Mitch R. Velez', image: 'students/vincent-velez.webp' },
      { name: 'Rodrigo Philip M. Vivo III', image: 'students/rodrigo-vivo.webp' }
    ],
    other: [      
      { title: 'United and solid!', image: 'other/classroom.webp' },
    ]
  },  
  {
    id: '422G',
    title: '422-G',
    adviser: { name: 'Teresita N. Alves', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Verna T. Miranda', shortName: 'Verna Miranda' },
      { role: 'Vice-President', name: 'Amillie Charito Jewel A. Japa', shortName: 'Amilie Japa' },
      { role: 'Secretary', name: 'Aileen C. Singson', shortName: 'Aileen Singson' },
      { role: 'Treasurer', name: 'Bernadette C. Lopez', shortName: 'Bernadette Lopez' },
      { role: 'P.R.O.', name: 'Brenda Joy O. Poblete', shortName: 'Brenda Poblete' },
      { role: 'Sgt. at Arms', name: 'Miriam O. Santos', shortName: 'Miriam Santos' }
    ],
    students: [
      { name: 'Evarose A. Alvarez', image: 'students/evarose-alvarez.webp' },
      { name: 'Joan T. Apelo', image: 'students/joan-apelo.webp' },
      { name: 'Rowena S. Baguino', image: 'students/rowena-baguino.webp' },
      { name: 'Myra S. Batac', image: 'students/myra-batac.webp' },
      { name: 'Ma. Lilibeth V. Batungbakal', image: 'students/lilibeth-batungbakal.webp' },
      { name: 'Veronica L. Bautista', image: 'students/veronica-bautista.webp' },
      { name: 'Vivienne D. Bautista', image: 'students/vivienne-bautista.webp' },
      { name: 'Janette C. Benemerito', image: 'students/janette-benemerito.webp' },
      { name: 'Angelica C. Bien', image: 'students/angelica-bien.webp' },
      { name: 'Lizza E. Cabarles', image: 'students/lizza-cabarles.webp' },
      { name: 'Anna Cielo Vic B. Canlas', image: 'students/anna-canlas.webp' },
      { name: 'Ma. Theresa P. Carlos', image: 'students/theresa-carlos.webp' },
      { name: 'Ma. Arlene S. Castillo', image: 'students/arlene-castillo.webp' },
      { name: 'Mary Rose C. De Castro', image: 'students/mary-decastro.webp' },
      { name: 'Sheila R. Castro', image: 'students/sheila-castro.webp' },
      { name: 'Sonia J. Cordoviz', image: 'students/sonia-cordoviz.webp' },
      { name: 'Aileen G. Cura', image: 'students/aileen-cura.webp' },
      { name: 'Mary Grace A. Delgado', image: 'students/mary-delgado.webp' },
      { name: 'Theresa Angela K. Dismas', image: 'students/theresa-dismas.webp' },
      { name: 'Anna Bernardita M. Enriquez', image: 'students/anna-enriquez.webp' },
      { name: 'Ma. Millicent C. Esberto', image: 'students/millicent-esberto.webp' },
      { name: 'Romela F. Faeldonia', image: 'students/romela-faeldonia.webp' },
      { name: 'Gina Maria C. Gener', image: 'students/gina-gener.webp' },
      { name: 'Jocelyn S. Gapo', image: 'students/jocelyn-gapo.webp' },
      { name: 'Fatima A. De Gorostiza', image: 'students/fatima-degorostiza.webp' },
      { name: 'Ma. Joan Gualberto', image: 'students/joan-gualberto.webp' },
      { name: 'Carmina Fatima V. De Guzman', image: 'students/carmina-deguzman.webp' },
      { name: 'Amillie Charito Jewel A. Japa', image: 'students/amillie-japa.webp' },
      { name: 'Myra Constancia B. Lachica', image: 'students/myra-lachica.webp' },
      { name: 'Josephine C. Lampa', image: 'students/josephine-lampa.webp' },
      { name: 'Bernadette C. Lopez', image: 'students/bernadette-lopez.webp' },
      { name: 'Marilou J. Mendoza', image: 'students/marilou-mendoza.webp' },
      { name: 'Jennifer C. Meneses', image: 'students/jennifer-meneses.webp' },
      { name: 'Verna T. Miranda', image: 'students/verna-miranda.webp' },
      { name: 'Janet C. Pineda', image: 'students/janet-pineda.webp' },
      { name: 'Brenda Joy O. Poblete', image: 'students/brenda-poblete.webp' },
      { name: 'Gloria D. Ramos', image: 'students/gloria-ramos.webp' },
      { name: 'Anne Michelle P. Reyes', image: 'students/anne-reyes.webp' },
      { name: 'Marisa P. De Los Reyes', image: 'students/marisa-delosreyes.webp' },
      { name: 'Rosario C. Sandoval', image: 'students/rosario-sandoval.webp' },
      { name: 'Ma. Cristina M. Santos', image: 'students/cristina-santos.webp' },
      { name: 'Miriam O. Santos', image: 'students/miriam-santos.webp' },
      { name: 'Ma. Nereza B. Santuyo', image: 'students/nereza-santuyo.webp' },
      { name: 'Ma. Theresa S. Sena', image: 'students/theresa-sena.webp' },
      { name: 'Aileen C. Singson', image: 'students/aileen-singson.webp' },
      { name: 'Liza D. Solis', image: 'students/liza-solis.webp' },
      { name: 'Anna Mae Tan', image: 'students/anna-tan.webp' },
      { name: 'Maribeth A. Tan', image: 'students/maribeth-tan.webp' },
      { name: 'Anita Flordeliza I. Tango', image: 'students/anita-tango.webp' },
      { name: 'Lorelie B. Tiopes', image: 'students/lorelie-tiopes.webp' },
      { name: 'Melinda B. Tolentino', image: 'students/melinda-tolentino.webp' },
      { name: 'Mae Lahnee A. Unite', image: 'students/mae-unite.webp' },
      { name: 'Ma. Jennifer N. Vidal', image: 'students/jennifer-vidal.webp' },
      { name: 'Marie Abegail P. Villadolid', image: 'students/marie-villadolid.webp' },
      { name: 'Ma. Jennifer S. Villanueva', image: 'students/jennifer-villanueva.webp' }
    ],
    other: [      
    ]
  },
  {
    id: '422B',
    title: '422-B',
    adviser: { name: 'Teresita Y. Santos', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Garrick Van V. Alumisin', shortName: 'Garrick Alumisin' },
      { role: 'Vice-President', name: 'Robert S. Jusay', shortName: 'Robert Jusay' },
      { role: 'Secretary', name: 'Gavini C. Pancho', shortName: 'Gavini Pancho' },
      { role: 'Treasurer', name: 'Roberto I. Belda', shortName: 'Roberto Belda' },
      { role: 'P.R.O.', name: 'Neil John V. Briones', shortName: 'Neil Briones' },
      { role: 'Sgt. at Arms', name: 'Cesar V. Dalde Jr.', shortName: 'Cesar Dalde' }
    ],
    students: [
      { name: 'Geoffrey F. Abello', image: 'students/geoffrey-abello.webp' },
      { name: 'Marcelino J. Alejo Jr.', image: 'students/marcelino-alejo.webp' },
      { name: 'Garrick Van V. Alumisin', image: 'students/garrick-alumisin.webp' },
      { name: 'Bernabe Barr U. Ambrosio', image: 'students/bernabe-ambrosio.webp' },
      { name: 'Gilbert C. Ang', image: 'students/gilbert-ang.webp' },
      { name: 'Edwin I. Antonio', image: 'students/edwin-antonio.webp' },
      { name: 'Rommel E. Argenal', image: 'students/rommel-argenal.webp' },
      { name: 'Luisito D. Articulo', image: 'students/luisito-articulo.webp' },
      { name: 'Zeus R. Balagtas', image: 'students/zeus-balagtas.webp' },
      { name: 'Marlon R. Baltazar', image: 'students/marlon-baltazar.webp' },
      { name: 'Ariel G. Bartilet', image: 'students/ariel-bartilet.webp' },
      { name: 'Ramil D. Bataller', image: 'students/ramil-bataller.webp' },
      { name: 'Roberto I. Belda', image: 'students/roberto-belda.webp' },
      { name: 'Neil John V. Briones', image: 'students/neil-briones.webp' },
      { name: 'Victor L. Cabochan', image: 'students/victor-cabochan.webp' },
      { name: 'Paul John T. Camiring', image: 'students/paul-camiring.webp' },
      { name: 'Leoberdo S. Cortez', image: 'students/leoberdo-cortez.webp' },
      { name: 'Adonis P. Cruz', image: 'students/adonis-cruz.webp' },
      { name: 'Cesar V. Dalde Jr.', image: 'students/cesar-dalde.webp' },
      { name: 'Abraham B. Diaz', image: 'students/abraham-diaz.webp' },
      { name: 'Danilo C. Eulogio', image: 'students/danilo-eulogio.webp' },
      { name: 'Emmanuel C. Feliciano', image: 'students/emmanuel-feliciano.webp' },
      { name: 'Manuel Erwin O. Felipe', image: 'students/manuel-felipe.webp' },
      { name: 'Jaime Victor L. Gabriel', image: 'students/jaime-gabriel.webp' },
      { name: 'Dominic E. Javier', image: 'students/dominic-javier.webp' },
      { name: 'Robert Agustin A. De Jesus Jr.', image: 'students/robert-dejesus.webp' },
      { name: 'Robert S. Jusay', image: 'students/robert-jusay.webp' },
      { name: 'Alvin N. De Leon', image: 'students/alvin-deleon.webp' },
      { name: 'Ramil M. Mirando', image: 'students/ramil-mirando.webp' },
      { name: 'Sidney D. Munji', image: 'students/sidney-munji.webp' },
      { name: 'Manuel M. Oliveros', image: 'students/manuel-oliveros.webp' },
      { name: 'Dexter V. Pacheco', image: 'students/dexter-pacheco.webp' },
      { name: 'Pancrasio D. Pahilan', image: 'students/pancrasio-pahilan.webp' },
      { name: 'Alvin P. Palamos', image: 'students/alvin-palamos.webp' },
      { name: 'Gavini C. Pancho', image: 'students/gavini-pancho.webp' },
      { name: 'Andres Edgar R. Perez', image: 'students/andres-perez.webp' },
      { name: 'Jose Angelo S. Petelo', image: 'students/jose-petelo.webp' },
      { name: 'Miguel H. Podolig', image: 'students/miguel-podolig.webp' },
      { name: 'Primo L. Prado', image: 'students/primo-prado.webp' },
      { name: 'Michael Angelo A. Raymundo', image: 'students/michael-raymundo.webp' },
      { name: 'Carlito M. Redaja', image: 'students/carlito-redaja.webp' },
      { name: 'Roderick D. Reyes', image: 'students/roderick-reyes.webp' },
      { name: 'Severino T. Salaguinto Jr.', image: 'students/severino-salaguinto.webp' },
      { name: 'Hector Joseph E. Samson', image: 'students/hector-samson.webp' },
      { name: 'Eric F. Santos', image: 'students/eric-santos.webp' },
      { name: 'Menardo G. Soliven', image: 'students/menardo-soliven.webp' },
      { name: 'Luisito G. Tirados', image: 'students/luisito-tirados.webp' },
      { name: 'Alexander R. Torres Jr.', image: 'students/alexander-torres.webp' },
      { name: 'Alexander D. Valmeo', image: 'students/alexander-valmeo.webp' },
      { name: 'Rogelio Velicaria', image: 'students/rogelio-velicaria.webp' },
      { name: 'Edgar R. Ventanilla', image: 'students/edgar-ventanilla.webp' },
      { name: 'Reginaldo S. Villanueva', image: 'students/reginaldo-villanueva.webp' },
      { name: 'Byron M. Villegas', image: 'students/byron-villegas.webp' },
      { name: 'Florito L. Yalung', image: 'students/florito-yalung.webp' },
      { name: 'Albert Q. Yamson III', image: 'students/albert-yamson.webp' }
    ],
    other: []
  },
  {
    id: '413G',
    title: '413-G',
    adviser: { name: 'Ester L. Abesamis', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Ma. Cecilia B. Magpoc', shortName: 'Cecilia Magpoc' },
      { role: 'Vice-President', name: 'Edlyn C. Carbungco', shortName: 'Edlyn Carbungco' },
      { role: 'Secretary', name: 'Ma. Theresa D. Ramos', shortName: 'Theresa Ramos' },
      { role: 'Treasurer', name: 'Ma. Aileen A. Macalalad', shortName: 'Aileen Macalalad' },
      { role: 'P.R.O.', name: 'Jennifer Marie E. Opeña', shortName: 'Jennifer Opeña' },
      { role: 'Sgt. at Arms', name: 'Marie Catherine C. Medalla', shortName: 'Catherine Medalla' }
    ],
    students: [
      { name: 'Ma. Ana A. Acosta', image: 'students/ana-acosta.webp' },
      { name: 'Maritesse U. Agtalao', image: 'students/maritesse-agtalao.webp' },
      { name: 'Ma. Leidail J. Alemania', image: 'students/leidail-alemania.webp' },
      { name: 'Joan L. Antalan', image: 'students/joan-antalan.webp' },
      { name: 'Juvy Judith B. Apo', image: 'students/juvy-apo.webp' },
      { name: 'Ma. Carmaencita D. Arguelles', image: 'students/carmaencita-arguelles.webp' },
      { name: 'Gladys Mary Joseph B. Asuncion', image: 'students/gladys-asuncion.webp' },
      { name: 'Gemma S.Bantug', image: 'students/gemma-bantug.webp' },
      { name: 'Carminda R. Bernardo', image: 'students/carminda-bernardo.webp' },
      { name: 'Rosalina C. Canlas', image: 'students/rosalina-canlas.webp' },
      { name: 'Ma. Maricris T. Carandang', image: 'students/maricris-carandang.webp' },
      { name: 'Edlyn C. Carbungco', image: 'students/edlyn-carbungco.webp' },
      { name: 'Ma. Cristina F. Crisostomo', image: 'students/cristina-crisostomo.webp' },
      { name: 'Ma. Shiegella Q. Daulat', image: 'students/shiegella-daulat.webp' },
      { name: 'Mely Fe T.S. Dieza', image: 'students/mely-dieza.webp' },
      { name: 'Debbie Dominica C. Dubal', image: 'students/debbie-dubal.webp' },
      { name: 'Regina B. Dujua', image: 'students/regina-dujua.webp' },
      { name: 'Pamela C. Dumlao', image: 'students/pamela-dumlao.webp' },
      { name: 'Ma. Carla S. Esquivias', image: 'students/carla-esquivas.webp' },
      { name: 'Brenna B. Evangelista', image: 'students/brenna-evangelista.webp' },
      { name: 'Mary Joy M. Flores', image: 'students/mary-flores.webp' },
      { name: 'Lilibeth F. Galang', image: 'students/lilibeth-galang.webp' },
      { name: 'Arlene G. Gonzales', image: 'students/arlene-gonzales.webp' },
      { name: 'Ma. Theresa T. Gorospe', image: 'students/theresa-gorospe.webp' },
      { name: 'Alarnie G. De Guia', image: 'students/alarnie-deguia.webp' },
      { name: 'Johnaida V. Gutierrez', image: 'students/johnaida-gutierrez.webp' },
      { name: 'Laura A. De Guzman', image: 'students/laura-deguzman.webp' },
      { name: 'Helen Y. Indelible', image: 'students/helen-indelible.webp' },
      { name: 'Carol R. Lagrisola', image: 'students/carol-lagrisola.webp' },
      { name: 'Leslie A. Lava', image: 'students/leslie-lava.webp' },
      { name: 'Mary Grace P. De Leon', image: 'students/mary-deleon.webp' },
      { name: 'Ma. Aileen A. Macalalad', image: 'students/aileen-macalalad.webp' },
      { name: 'Ma. Cecilia B. Magpoc', image: 'students/cecilia-magpoc.webp' },
      { name: 'Olivia V. Mallare', image: 'students/olivia-mallare.webp' },
      { name: 'Ma. Cristina T. Mangubat', image: 'students/cristina-mangubat.webp' },
      { name: 'Mary Ann Mona Gale L. Manuel', image: 'students/mary-manuel.webp' },
      { name: 'Marie Catherine C. Medalla', image: 'students/marie-medalla.webp' },
      { name: 'Michelle M. Mendoza', image: 'students/michelle-mendoza.webp' },
      { name: 'Marianne L. Molina', image: 'students/marianne-molina.webp' },
      { name: 'Leah A. Novenario', image: 'students/leah-novenario.webp' },
      { name: 'Jennifer Marie E. Opeña', image: 'students/jennifer-opena.webp' },
      { name: 'Ma. Bernadette G. Orencia', image: 'students/bernadette-orencia.webp' },
      { name: 'Rosanne D. Oscaris', image: 'students/rosanne-oscaris.webp' },
      { name: 'Rubelita Pabulayan', image: 'students/rubelita-pabulayan.webp' },
      { name: 'Ma. Caridad D. Dela Peña', image: 'students/caridad-delapena.webp' },
      { name: 'Ma. Theresa D. Ramos', image: 'students/theresa-ramos.webp' },
      { name: 'Kristine Lizza I. Rocamora', image: 'students/kristine-rocamora.webp' },
      { name: 'Elaine V. Salvador', image: 'students/elaine-salvador.webp' },
      { name: 'Bernadette M. Soller', image: 'students/bernadette-soller.webp' },
      { name: 'Ana-Liza R. Suing', image: 'students/analiza-suing.webp' },
      { name: 'Ma. Victoria M. Tesoro', image: 'students/victoria-tesoro.webp' },
      { name: 'Janet M. Tibayan', image: 'students/janet-tibayan.webp' },
      { name: 'Ma. Felipa H. Velasquez', image: 'students/felipa-velasquez.webp' }
    ],
    other: [      
      { title: 'Familiar faces?', image: 'other/classroom.webp' },
    ]
  },
  {
    id: '413B',
    title: '413-B',
    adviser: { name: 'Angeles R. Mendoza Jr.', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Edwin Q. Rosario', shortName: 'Edwin Rosario' },
      { role: 'Vice-President', name: 'Enrico M. Valdez', shortName: 'Enrico Valdez' },
      { role: 'Secretary', name: 'Harold L. Vibal', shortName: 'Harold Vibal' },
      { role: 'Treasurer', name: 'Jose Rico A. Lim', shortName: 'Jose Rico Lim' },
      { role: 'P.R.O.', name: 'Robin L. Mariano', shortName: 'Robin Mariano' },
      { role: 'Sgt. at Arms', name: 'Edwin Raymond C. Malimban', shortName: 'Edwin Malimban' }
    ],
    students: [
      { name: 'Neil Zorester L. Agbisit', image: 'students/neil-agbisit.webp' },
      { name: 'Dante L. Alday', image: 'students/dante-alday.webp' },
      { name: 'Aldous P. Aliento', image: 'students/aldous-aliento.webp' },
      { name: 'Omar A. Asuncion', image: 'students/omar-asuncion.webp' },
      { name: 'Christopher S. Bautista', image: 'students/christopher-bautista.webp' },
      { name: 'Polly T. Blanco', image: 'students/polly-blanco.webp' },
      { name: 'Eric A. Calumpang', image: 'students/eric-calumpang.webp' },
      { name: 'Jo Ben M. Chua', image: 'students/jo-chua.webp' },
      { name: 'Cid-Lance O. Cos', image: 'students/cid-cos.webp' },
      { name: 'Jesus Roberto T. David', image: 'students/jesus-david.webp' },
      { name: 'Joseph B. David', image: 'students/joseph-david.webp' },
      { name: 'Roderick D. David', image: 'students/roderick-david.webp' },
      { name: 'Robinson M. Dinglasan', image: 'students/robinson-dinglasan.webp' },
      { name: 'Antonio D. Fernandez Jr.', image: 'students/antonio-fernandez.webp' },
      { name: 'Dalmacio P. Florencio', image: 'students/dalmacio-florencio.webp' },
      { name: 'Joseph Dennis V. Jovero', image: 'students/joseph-jovero.webp' },
      { name: 'Victor R. Labarinto', image: 'students/victor-labarinto.webp' },
      { name: 'Ronald F. Lacuesta', image: 'students/ronald-lacuesta.webp' },
      { name: 'Conrad Juvenal R. Lagustan', image: 'students/conrad-lagustan.webp' },
      { name: 'Edward R. Leachon', image: 'students/edward-leachon.webp' },
      { name: 'Jose Rico A. Lim', image: 'students/jose-lim.webp' },
      { name: 'Derrick Antonio B. Lopez', image: 'students/derrick-lopez.webp' },
      { name: 'Frederick Emmanuel F. Lopez', image: 'students/frederick-lopez.webp' },
      { name: 'Edwin Raymond C. Malimban', image: 'students/edwin-malimban.webp' },
      { name: 'Roberto P. Manalo', image: 'students/roberto-manalo.webp' },
      { name: 'Joseph T. Maniego', image: 'students/joseph-maniego.webp' },
      { name: 'Dennis B. Manlangit', image: 'students/dennis-manlangit.webp' },
      { name: 'Robin L. Mariano', image: 'students/robin-mariano.webp' },
      { name: 'Michael L. Morales', image: 'students/michael-morales.webp' },
      { name: 'Jose Eriberto G. Pacquing', image: 'students/jose-pacquing.webp' },
      { name: 'Jonathan V. Pagayon', image: 'students/jonathan-pagayon.webp' },
      { name: 'Pierre F. Palaad', image: 'students/pierre-palaad.webp' },
      { name: 'Vinson S. Perea', image: 'students/vinson-perea.webp' },
      { name: 'Conrado C. Pineda Jr.', image: 'students/conrado-pineda.webp' },
      { name: 'Heinrich G. Presas', image: 'students/heinrich-presas.webp' },
      { name: 'Neil T. Rentar', image: 'students/neil-rentar.webp' },
      { name: 'Joseph J. Reyes', image: 'students/joseph-reyes.webp' },
      { name: 'Edwin Q. Rosario', image: 'students/edwin-rosario.webp' },
      { name: 'Lyndon C. Rubio', image: 'students/lyndon-rubio.webp' },
      { name: 'Dennis D. Sacdalan', image: 'students/dennis-sacdalan.webp' },
      { name: 'Daniel G. San Diego', image: 'students/daniel-sandiego.webp' },
      { name: 'Rosauro R. Tagle Jr.', image: 'students/rosauro-tagle.webp' },
      { name: 'Edwin B. Tejada', image: 'students/edwin-tejada.webp' },
      { name: 'Edward B. Tan', image: 'students/edward-tan.webp' },
      { name: 'Roberth B. Tolentino', image: 'students/roberth-tolentino.webp' },
      { name: 'Rogelio B. Tuibeo', image: 'students/rogelio-tuibeo.webp' },
      { name: 'Enrico M. Valdez', image: 'students/enrico-valdez.webp' },
      { name: 'Joel L. Valena', image: 'students/joel-valena.webp' },
      { name: 'Teodoro E. Vasquez II', image: 'students/teodoro-vasquez.webp' },
      { name: 'Harold L. Vibal', image: 'students/harold-vibal.webp' },
      { name: 'Antonio G. Villareal', image: 'students/antonio-villareal.webp' },
      { name: 'Edmund E. Villaroman', image: 'students/edmund-villaroman.webp' },
      { name: 'Jose Pablo Viray', image: 'students/jose-viray.webp' },
      { name: 'Joseph G. Zipagang', image: 'students/joseph-zipagang.webp' }
    ],
    other: [      
      { title: 'Oh no!', image: 'other/classroom.webp' },
    ]
  },  
  {
    id: '423G',
    title: '423-G',
    adviser: { name: 'Belinda N. Gallamos', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Jocelyn C. Hechanova', shortName: 'Jocelyn Hechanova' },
      { role: 'Vice-President', name: 'Raquel N. Magistrado', shortName: 'Raquel Magistrado' },
      { role: 'Secretary', name: 'Maria Angelica M. Rena', shortName: 'Angelica Rena' },
      { role: 'Treasurer', name: 'Maria Joy V. Osea', shortName: 'Joy Osea' },
      { role: 'P.R.O.', name: 'Leila H. Palma', shortName: 'Leila Palma' },
      { role: 'Sgt. at Arms', name: 'Jonathan G. Baltazar', shortName: 'Jonathan Baltazar' }
    ],
    students: [
      { name: 'Maria Divina A. Alvarado', image: 'students/maria-alvarado.webp' },
      { name: 'Carolina G. Artates', image: 'students/carolina-artates.webp' },
      { name: 'Maria Angelita A. Baisa', image: 'students/maria-baisa.webp' },
      { name: 'Jonathan G. Baltazar', image: 'students/jonathan-baltazar.webp' },
      { name: 'Marissa C. Bautista', image: 'students/marissa-bautista.webp' },
      { name: 'Melanie M. Bayro', image: 'students/melanie-bayro.webp' },
      { name: 'Eliza F. Cabantig', image: 'students/eliza-cabantig.webp' },
      { name: 'Elizabeth L. Caparas', image: 'students/elizabeth-caparas.webp' },
      { name: 'Mitos R. Cayanan', image: 'students/mitos-cayanan.webp' },
      { name: 'Miriam S. Concepcion', image: 'students/miriam-concepcion.webp' },
      { name: 'Agnes M. Crelencia', image: 'students/agnes-crelencia.webp' },
      { name: 'Criselda L. Cruz', image: 'students/criselda-cruz.webp' },
      { name: 'Marinette Ann R. Cruz', image: 'students/marinette-cruz.webp' },
      { name: 'Corinne Y. Cubias', image: 'students/corinne-cubias.webp' },
      { name: 'Maria Vina S. Dinglasan', image: 'students/maria-dinglasan.webp' },
      { name: 'Perla Florida L. Dirige', image: 'students/perla-dirige.webp' },
      { name: 'Armida C. Estanislao', image: 'students/armida-estanislao.webp' },
      { name: 'Mary Ann V. Esteban', image: 'students/mary-esteban.webp' },
      { name: 'Jocelyn C. Hechanova', image: 'students/jocelyn-hechanova.webp' },
      { name: 'Raquel N. Magistrado', image: 'students/raquel-magistrado.webp' },
      { name: 'Nannette G. Manalese', image: 'students/nannette-manalese.webp' },
      { name: 'Maria Josefina M. Manalo', image: 'students/maria-manalo.webp' },
      { name: 'Elyn T. Mangrobang', image: 'students/elyn-mangrobang.webp' },
      { name: 'Lyn Leni L. Mendoza', image: 'students/lyn-mendoza.webp' },
      { name: 'Molly Ann S. Mendoza', image: 'students/molly-mendoza.webp' },
      { name: 'Minabel Melchora B. Mercado', image: 'students/minabel-mercado.webp' },
      { name: 'Cesarina B. Minas', image: 'students/cesarina-minas.webp' },
      { name: 'Aileen B. Molina', image: 'students/aileen-molina.webp' },
      { name: 'Annalyn G. Oliveros', image: 'students/annalyn-oliveros.webp' },
      { name: 'Roby Ann Charmagne A. Opeña', image: 'students/roby-opena.webp' },
      { name: 'Yvonne M. Orlinda', image: 'students/yvonne-orlinda.webp' },
      { name: 'Maria Joy V. Osea', image: 'students/maria-osea.webp' },
      { name: 'Leila H. Palma', image: 'students/leila-palma.webp' },
      { name: 'Grace B. Panganiban', image: 'students/grace-panganiban.webp' },
      { name: 'Miriam V. Pangilinan', image: 'students/miriam-pangilinan.webp' },
      { name: 'Alma T. Quitangon', image: 'students/alma-quitangon.webp' },
      { name: 'Luisa Trinita S. Rañada', image: 'students/luisa-ranada.webp' },
      { name: 'Maria Angelica M. Reña', image: 'students/maria-rena.webp' },
      { name: 'Anna Lisa D. Rivera', image: 'students/anna-rivera.webp' },
      { name: 'Christine P. Salando', image: 'students/christine-salando.webp' },
      { name: 'Relynn F. Salanguit', image: 'students/relynn-salanguit.webp' },
      { name: 'Mary Claire N. Serra', image: 'students/mary-serra.webp' },
      { name: 'Maria Rosanna S. Sian', image: 'students/maria-sian.webp' },
      { name: 'Jessica Ann M. Silo', image: 'students/jessica-silo.webp' },
      { name: 'Arlene V. Sta. Ines', image: 'students/arlene-staines.webp' },
      { name: 'Marie Phyllis E. Tablada', image: 'students/marie-tablada.webp' },
      { name: 'Mary Beth A. Tan', image: 'students/mary-tan.webp' },
      { name: 'Monica A. Tungol', image: 'students/monica-tungol.webp' },
      { name: 'Lourdes M. Velasco', image: 'students/lourdes-velasco.webp' },
      { name: 'Joanne Fabianne M. Viado', image: 'students/joanne-viado.webp' },
      { name: 'Mary Ann I. Vuelba', image: 'students/mary-vuelba.webp' },
      { name: 'Helen Grace A. Yanca', image: 'students/helen-yanca.webp' },
      { name: 'Janet M. Yasoña', image: 'students/janet-yasona.webp' },
      { name: 'Leilanie P. Zaldarriaga', image: 'students/leilanie-zaldarriaga.webp' }
    ],
    other: [      
      { title: 'Nice, sweet, and pretty', image: 'other/classroom.webp' },
    ]
  },
  {
    id: '423B',
    title: '423-B',
    adviser: { name: 'Alexander Tagaro', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Farley John M. Javier', shortName: 'Farley Javier' },
      { role: 'Vice-President', name: 'Remlee M. Dela Cruz', shortName: 'Remlee Dela Cruz' },
      { role: 'Secretary', name: 'Romeo S. Diaz Jr.', shortName: 'Romeo Diaz Jr.' },
      { role: 'Treasurer', name: 'Von Ferdinand O. Villagarcia', shortName: 'Von Villagarcia' },
      { role: 'P.R.O.', name: 'Jericho C. Ponce', shortName: 'Jericho Ponce' },
      { role: 'Sgt. at Arms', name: 'Antonio P. Agustin Jr.', shortName: 'Antonio Agustin' }
    ],
    students: [
      { name: 'Antonio P. Agustin Jr.', image: 'students/antonio-agustin.webp' },
      { name: 'Herman C. Aliangan Jr.', image: 'students/herman-aliangan.webp' },
      { name: 'Gilbert B. Anos', image: 'students/gilbert-anos.webp' },
      { name: 'Roy T. Benavides', image: 'students/roy-benavides.webp' },
      { name: 'Raymond P. Borcena', image: 'students/raymond-borcena.webp' },
      { name: 'Darmindar S. Brar', image: 'students/darmindar-brar.webp' },
      { name: 'Romeo N. Bucala', image: 'students/romeo-bucala.webp' },
      { name: 'Alfredo V. Camacho Jr.', image: 'students/alfredo-camacho.webp' },
      { name: 'John B. Candoleta', image: 'students/john-candoleta.webp' },
      { name: 'James Walter P. Capili', image: 'students/james-capili.webp' },
      { name: 'Jojo Rex Casaje', image: 'students/jojo-casaje.webp' },
      { name: 'Martin Omar J. Concepcion', image: 'students/martin-concepcion.webp' },
      { name: 'Fernando O. Cosme', image: 'students/fernando-cosme.webp' },
      { name: 'Remlee M. Dela Cruz', image: 'students/remlee-delacruz.webp' },
      { name: 'Romeo S. Diaz Jr.', image: 'students/romeo-diaz.webp' },
      { name: 'Romel C. Dinglasan', image: 'students/romel-dinglasan.webp' },
      { name: 'Rolando B. Duculan Jr.', image: 'students/rolando-duculan.webp' },
      { name: 'Ricardo M. Encarnacion', image: 'students/ricardo-encarnacion.webp' },
      { name: 'Leandro Edizer R. Enoval', image: 'students/leandro-enoval.webp' },
      { name: 'Philipp E. Erestain', image: 'students/philipp-erestain.webp' },
      { name: 'Aldrin George E. Floro', image: 'students/aldrin-floro.webp' },
      { name: 'Marvin T. Frondoso', image: 'students/marvin-frondoso.webp' },
      { name: 'Frederick F. Garcia', image: 'students/frederick-garcia.webp' },
      { name: 'Jason M. Gonzales', image: 'students/jason-gonzales.webp' },
      { name: 'Lemuel R. De Guzman', image: 'students/lemuel-deguzman.webp' },
      { name: 'Heartzell Jim B. Jardio', image: 'students/heartzell-jardio.webp' },
      { name: 'Farley John M. Javier', image: 'students/farley-javier.webp' },
      { name: 'Jose Angelito L. Leal', image: 'students/jose-leal.webp' },
      { name: 'Roberto C. Leonardo', image: 'students/roberto-leonardo.webp' },
      { name: 'Noriel Rayond C. Lim', image: 'students/noriel-lim.webp' },
      { name: 'Eduardo Z. Lucero Jr.', image: 'students/eduardo-lucero.webp' },
      { name: 'Erwin S. Marquez', image: 'students/erwin-marquez.webp' },
      { name: 'Nilo U. Martinez II', image: 'students/nilo-martinez.webp' },
      { name: 'John Joseph A. Morales', image: 'students/john-morales.webp' },
      { name: 'Edwin M. Natividad', image: 'students/edwin-natividad.webp' },
      { name: 'Michael A. Olesco', image: 'students/michael-olesco.webp' },
      { name: 'Vincent B. Olfindo', image: 'students/vincent-olfindo.webp' },
      { name: 'Edwin R. De Pacina', image: 'students/edwin-depacina.webp' },
      { name: 'Paul Eric S. Padilla', image: 'students/paul-padilla.webp' },
      { name: 'Edwin G. Paras', image: 'students/edwin-paras.webp' },
      { name: 'Paul D. Perez', image: 'students/paul-perez.webp' },
      { name: 'Jericho C. Ponce', image: 'students/jericho-ponce.webp' },
      { name: 'Arnold G. Rodriguez', image: 'students/arnold-rodriguez.webp' },
      { name: 'Ronald R. Sanchez', image: 'students/ronald-sanchez.webp' },
      { name: 'Roderick C. Santiago', image: 'students/roderick-santiago.webp' },
      { name: 'Rafael Santos', image: 'students/rafael-santos.webp' },
      { name: 'Mariano L. Serrano III', image: 'students/mariano-serrano.webp' },
      { name: 'Ruel Y. Sibal', image: 'students/ruel-sibal.webp' },
      { name: 'Juno Antonio A. Taco Jr.', image: 'students/juno-taco.webp' },
      { name: 'Rogelio B. Tapang', image: 'students/rogelio-tapang.webp' },
      { name: 'Eric B. Tee', image: 'students/eric-tee.webp' },
      { name: 'Jojo M. Uy', image: 'students/jojo-uy.webp' },
      { name: 'Joel Velasco', image: 'students/joel-velasco.webp' },
      { name: 'Romeo T. Vendivil', image: 'students/romeo-vendivil.webp' },
      { name: 'Von Ferdinand O. Villagarcia', image: 'students/von-villagarcia.webp' }
    ],
    other: [
    ]
  },
  {
    id: '414G',
    title: '414-G',
    adviser: { name: 'Marissa Casas', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Ma. Shirley C. Pascua', shortName: 'Shirley Pascua' },
      { role: 'Vice-President', name: 'Socorro Laarni B. Edurise', shortName: 'Socorro Edurise' },
      { role: 'Secretary', name: 'Pilar E. Panganiban', shortName: 'Pilar Panganiban' },
      { role: 'Treasurer', name: 'Rowena M. Reyes', shortName: 'Rowena Reyes' },
      { role: 'P.R.O.', name: 'Mary Grace N. Laudencia', shortName: 'Mary Grace Laudencia' },
      { role: 'Sgt. at Arms', name: 'Romina Sharon E. Macabeo', shortName: 'Romina Macabeo' }
    ],
    students: [
      { name: 'Minerva A. Agomaa', image: 'students/minerva-agomaa.webp' },
      { name: 'Aileen Z. Agulto', image: 'students/aileen-agulto.webp' },
      { name: 'Adrienne M. Amponin', image: 'students/adrienne-amponin.webp' },
      { name: 'Ma. Isabel M. Antonio', image: 'students/isabel-antonio.webp' },
      { name: 'Ma. Michelle R. Arquisola', image: 'students/michelle-arquisola.webp' },
      { name: 'Maria Elenita V. Bacani', image: 'students/maria-bacani.webp' },
      { name: 'Loida D. Basilio', image: 'students/loida-basilio.webp' },
      { name: 'Aileen V. Baylon', image: 'students/aileen-baylon.webp' },
      { name: 'Brenda B. Bernabe', image: 'students/brenda-bernabe.webp' },
      { name: 'Marissa F. Calderon', image: 'students/marissa-calderon.webp' },
      { name: 'Zorayda M. Capili', image: 'students/zorayda-capili.webp' },
      { name: 'Ma. Cecilia B. Carbonell', image: 'students/cecilia-carbonell.webp' },
      { name: 'Rowena B. Cruz', image: 'students/rowena-cruz.webp' },
      { name: 'Laarne B. Dumag', image: 'students/laarne-dumag.webp' },
      { name: 'Socorro Laarni B. Edurise', image: 'students/socorro-edurise.webp' },
      { name: 'Sheba B. Felio', image: 'students/sheba-felio.webp' },
      { name: 'Gina G. Galicto', image: 'students/gina-galicto.webp' },
      { name: 'Ma. Carmelita E. Garcia', image: 'students/carmelita-garcia.webp' },
      { name: 'Menelea J. Gaytano', image: 'students/menelea-gaytano.webp' },
      { name: 'Gielza Theresita E. Guiang', image: 'students/gielza-guiang.webp' },
      { name: 'Gretel M. Ignacio', image: 'students/gretel-ignacio.webp' },
      { name: 'Ma. Theresita L. Javillo', image: 'students/theresita-javillo.webp' },
      { name: 'Luningning O. La Rosa', image: 'students/luningning-larosa.webp' },
      { name: 'Ma. Carmine A. Lasam', image: 'students/carmine-lasam.webp' },
      { name: 'Mary Grace N. Laudencia', image: 'students/mary-laudencia.webp' },
      { name: 'Rachelle Maria F. Libunao', image: 'students/rachelle-libunao.webp' },
      { name: 'Romina Sharon E. Macabeo', image: 'students/romina-macabeo.webp' },
      { name: 'Cinderella C. Macatangay', image: 'students/cinderella-macatangay.webp' },
      { name: 'Mylyn C. Magpantay', image: 'students/mylyn-magpantay.webp' },
      { name: 'Ma. Donna Adora S. Manlutac', image: 'students/donna-manlutac.webp' },
      { name: 'Geraldine Z. Marasigan', image: 'students/geraldine-marasigan.webp' },
      { name: 'Gizelle S. Martinez', image: 'students/gizelle-martinez.webp' },
      { name: 'Ivy Lily F. Mendoza', image: 'students/ivy-mendoza.webp' },
      { name: 'Wilmina S. Merginio', image: 'students/wilmina-merginio.webp' },
      { name: 'Rosalyn G. Nadong', image: 'students/rosalyn-nadong.webp' },
      { name: 'Ma. Criselda T. Ochoa', image: 'students/criselda-ochoa.webp' },
      { name: 'Dina D. Ordona', image: 'students/dina-ordona.webp' },
      { name: 'Ma. Sheila B. Pacheco', image: 'students/sheila-pacheco.webp' },
      { name: 'Pilar E. Panganiban', image: 'students/pilar-panganiban.webp' },
      { name: 'Ma. Shirley C. Pascua', image: 'students/shirley-pascua.webp' },
      { name: 'Grace Anne G. Presas', image: 'students/grace-presas.webp' },
      { name: 'Ma. Violeta P. Reyes', image: 'students/violeta-reyes.webp' },
      { name: 'Rowena M. Reyes', image: 'students/rowena-reyes.webp' },
      { name: 'Ave Catherine D. Dela Rosa', image: 'students/ave-delarosa.webp' },
      { name: 'Alma M. Samonteza', image: 'students/alma-samonteza.webp' },
      { name: 'Ma. Christina A. Santos', image: 'students/christina-santos.webp' },
      { name: 'Cynthia May S. Sepulveda', image: 'students/cynthia-sepulveda.webp' },
      { name: 'Marichelle R. Soriano', image: 'students/marichelle-soriano.webp' },
      { name: 'Trecia C. Tayco', image: 'students/trecia-tayco.webp' },
      { name: 'Mary Claire S. Tenmatay', image: 'students/mary-tenmatay.webp' },
      { name: 'Yvonne Suzzette D. Villacorte', image: 'students/yvonne-villacorte.webp' },
      { name: 'Joan T. Villanueva', image: 'students/joan-villanueva.webp' }
    ],
    other: [
        { title: 'Camera shy?', image: 'other/classroom.webp' },
    ]
  },
  {
    id: '414B',
    title: '414-B',
    adviser: { name: 'Raymond Daniel H. Cruz', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Fernando Lino V. Natividad', shortName: 'Fernando Natividad' },
      { role: 'Vice-President', name: 'Fernan Harold R. Paylago', shortName: 'Harold Paylago' },
      { role: 'Secretary', name: 'Dennis Q. Alonzo', shortName: 'Dennis Alonzo' },
      { role: 'Treasurer', name: 'Angelico Arlantico', shortName: 'Angelico Arlantico' },
      { role: 'P.R.O.', name: 'Le Roy A. Fortunato', shortName: 'Leroy Fortunato' },
      { role: 'Sgt. at Arms', name: 'Eric Anthony R. Carandang', shortName: 'Eric Carandang' }
    ],
    students: [
      { name: 'Dennis Q. Alonzo', image: 'students/dennis-alonzo.webp' },
      { name: 'Rowelito R. Angeles', image: 'students/rowelito-angeles.webp' },
      { name: 'Justiniano F. Antonio Jr.', image: 'students/justiniano-antonio.webp' },
      { name: 'Angelico Arlantico', image: 'students/angelico-arlantico.webp' },
      { name: 'Narciso P. Atienza Jr.', image: 'students/narciso-atienza.webp' },
      { name: 'Allan G. Avellaneda', image: 'students/allan-avellaneda.webp' },
      { name: 'Hector Aniceto S. Bagalay', image: 'students/hector-bagalay.webp' },
      { name: 'Louiesito C. Bangco', image: 'students/louiesito-bangco.webp' },
      { name: 'Bernardo C. Barrios', image: 'students/bernardo-barrios.webp' },
      { name: 'Dante Y. Bautista', image: 'students/dante-bautista.webp' },
      { name: 'Erwin M. Burgos', image: 'students/erwin-burgos.webp' },
      { name: 'Adelbert Gerardo D. Burlas', image: 'students/adelbert-burlas.webp' },
      { name: 'Sancho O. Celedio', image: 'students/sancho-celedio.webp' },
      { name: 'Eric Anthony R. Carandang', image: 'students/eric-carandang.webp' },
      { name: 'Vicente D. Calayag Jr.', image: 'students/vicente-calayag.webp' },
      { name: 'Carlo M. Cadiz', image: 'students/carlo-cadiz.webp' },
      { name: 'Ronnie P. Cervantes', image: 'students/ronnie-cervantes.webp' },
      { name: 'Carlo M. Clemente', image: 'students/carlo-clemente.webp' },
      { name: 'Luis R. Dela Cruz III', image: 'students/luis-delacruz.webp' },
      { name: 'Allan S. Dumlao', image: 'students/allan-dumlao.webp' },
      { name: 'Randy M. Duran', image: 'students/randy-duran.webp' },
      { name: 'Jesus Mario G. Fernandez', image: 'students/jesus-fernandez.webp' },
      { name: 'Le Roy A. Fortunato', image: 'students/leroy-fortunato.webp' },
      { name: 'Deogracias S. Garcia', image: 'students/deogracias-garcia.webp' },
      { name: 'Clifford E. Gomez', image: 'students/clifford-gomez.webp' },
      { name: 'Conrado Rae H. De Leon', image: 'students/conrado-deleon.webp' },
      { name: 'Eric E. Manzano', image: 'students/eric-manzano.webp' },
      { name: 'Kirk Josuah R. Molina', image: 'students/kirk-molina.webp' },
      { name: 'Joseph Z. Mopas', image: 'students/joseph-mopas.webp' },
      { name: 'Fernando Lino V. Natividad', image: 'students/fernando-natividad.webp' },
      { name: 'Elme-Al O. Navera', image: 'students/elme-navera.webp' },
      { name: 'Oliver H. Olila', image: 'students/oliver-olila.webp' },
      { name: 'Roberto A. Ordonez', image: 'students/roberto-ordonez.webp' },
      { name: 'Remar B. Padlan', image: 'students/remar-padlan.webp' },
      { name: 'Fernan Harold R. Paylago', image: 'students/fernan-paylago.webp' },
      { name: 'Garry Luis M. Piamonte', image: 'students/garry-piamonte.webp' },
      { name: 'Raymond J. Pineda', image: 'students/raymond-pineda.webp' },
      { name: 'Clifford V. Rentino', image: 'students/clifford-rentino.webp' },
      { name: 'Mauro T. Roman', image: 'students/mauro-roman.webp' },
      { name: 'Rhoderick P. Del Rosario', image: 'students/rhoderick-delrosario.webp' },
      { name: 'Arnold L. Salaverria', image: 'students/arnold-salaverria.webp' },
      { name: 'Robin Orlando C. Samson', image: 'students/robin-samson.webp' },
      { name: 'Angelito G. Tan Jr.', image: 'students/angelito-tan.webp' },
      { name: 'John P. Tirona', image: 'students/john-tirona.webp' },
      { name: 'Alejandro E. Toledo Jr.', image: 'students/alejandro-toledo.webp' },
      { name: 'Joselito G. Tolentino', image: 'students/joselito-tolentino.webp' },
      { name: 'Marcelito B. Torres', image: 'students/marcelito-torres.webp' },
      { name: 'George P. Tubera', image: 'students/george-tubera.webp' },
      { name: 'Darwin N. Tungol', image: 'students/darwin-tungol.webp' },
      { name: 'Rommel M. Turbanos', image: 'students/rommel-turbanos.webp' },
      { name: 'Tirso M. Velasco', image: 'students/tirso-velasco.webp' },
      { name: 'Jose Mari C. Viviezca', image: 'students/jose-viviezca.webp' },
      { name: 'Kenneth L. Yam', image: 'students/kenneth-yam.webp' },
    ],
    other: [
        { title: 'Billiard hall tambays', image: 'other/classroom.webp' },
    ]
  },
  {
    id: '424G',
    title: '424-G',
    adviser: { name: 'Glicelda Berja', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Erlinda V. Alvarez II', shortName: 'Erlinda Alvarez II' },
      { role: 'Vice-President', name: 'Anabel I. Mangali', shortName: 'Anabel Mangali' },
      { role: 'Secretary', name: 'Anna Lisa M. Belen', shortName: 'Anna Lisa Belen' },
      { role: 'Treasurer', name: 'Ma. Lani V. Reyes', shortName: 'Lani Reyes' },
      { role: 'P.R.O.', name: 'Marietta C. Vicencio', shortName: 'Marietta Vicencio' },
      { role: 'Sgt. at Arms', name: 'Cristina A. Parulan', shortName: 'Cristina Parulan' }
    ],
    students: [
      { name: 'Mary Jane C. Abad', image: 'students/mary-abad.webp' },
      { name: 'Erlinda V. Alvarez II', image: 'students/erlinda-alvarez.webp' },
      { name: 'Michelle C. Basiloy', image: 'students/michelle-basiloy.webp' },
      { name: 'Anna Lisa M. Belen', image: 'students/anna-belen.webp' },
      { name: 'Ma. Teresa S. Bulatao', image: 'students/teresa-bulatao.webp' },
      { name: 'Jeremiah I. Castaneda', image: 'students/jeremiah-castaneda.webp' },
      { name: 'Hazel B. Centeno', image: 'students/hazel-centeno.webp' },
      { name: 'Arlinda J. Cesa', image: 'students/arlinda-cesa.webp' },
      { name: 'Ma. Esperanza P. Dajoyag', image: 'students/esperanza-dajoyag.webp' },
      { name: 'Sheryll Mae M. Dandan', image: 'students/sheryll-dandan.webp' },
      { name: 'Catherine M. Dilig', image: 'students/catherine-dilig.webp' },
      { name: 'Myra F. Enriquez', image: 'students/myra-enriquez.webp' },
      { name: 'Jossie P. Escalante', image: 'students/jossie-escalante.webp' },
      { name: 'Joahnna P. Esguerra', image: 'students/joahnna-esguerra.webp' },
      { name: 'Gloria O. Esperanza', image: 'students/gloria-esperanza.webp' },
      { name: 'Aurita B. Gabay', image: 'students/aurita-gabay.webp' },
      { name: 'Deanna G. Guirnalda', image: 'students/deanna-guirnalda.webp' },
      { name: 'Angelica R. Guy', image: 'students/angelica-guy.webp' },
      { name: 'Jennifer C. Llano', image: 'students/jennifer-llano.webp' },
      { name: 'Ruby Joy M. Lacorte', image: 'students/ruby-lacorte.webp' },
      { name: 'Mary Claire L. Lacuesta', image: 'students/mary-lacuesta.webp' },
      { name: 'Maria Clara B. Lasa', image: 'students/maria-lasa.webp' },
      { name: 'Maria Mai Monica C. Ledesma', image: 'students/maria-ledesma.webp' },
      { name: 'Ma. Cristina B. Malijan', image: 'students/cristina-malijan.webp' },
      { name: 'Catherine M. Maliwanag', image: 'students/catherine-maliwanag.webp' },
      { name: 'Irene R. Mamaril', image: 'students/irene-mamaril.webp' },
      { name: 'Lourdes Marie D. Mandap', image: 'students/lourdes-mandap.webp' },
      { name: 'Anabel I. Mangali', image: 'students/anabel-mangali.webp' },
      { name: 'Mary Grace A. Mendiola', image: 'students/mary-mendiola.webp' },
      { name: 'Lily Ann S. Mina', image: 'students/lily-mina.webp' },
      { name: 'Ma. Carolyn M. Nera', image: 'students/carolyn-nera.webp' },
      { name: 'Cristina A. Parulan', image: 'students/cristina-parulan.webp' },
      { name: 'Catherine P. Pascua', image: 'students/catherine-pascua.webp' },
      { name: 'Alodie L. Peñarubia', image: 'students/alodie-penarubia.webp' },
      { name: 'Ma. Lina D. Perpetua', image: 'students/lina-perpetua.webp' },
      { name: 'Karen L. Pitarde', image: 'students/karen-pitarde.webp' },
      { name: 'Floren R. Ragunton', image: 'students/floren-ragunton.webp' },
      { name: 'Lourdes C. Rasalan', image: 'students/lourdes-rasalan.webp' },
      { name: 'Arlene N. Reside', image: 'students/arlene-reside.webp' },
      { name: 'Ma. Lani V. Reyes', image: 'students/lani-reyes.webp' },
      { name: 'Rica Maria Antonette Z. Reyes', image: 'students/rica-reyes.webp' },
      { name: 'Marie Claire B. Romero', image: 'students/marie-romero.webp' },
      { name: 'Catherine M. Santos', image: 'students/catherine-santos.webp' },
      { name: 'Jennifer M. Santos', image: 'students/jennifer-santos.webp' },
      { name: 'Verna L. Santos', image: 'students/verna-santos.webp' },
      { name: 'Ma. Cristina R. Soriano', image: 'students/cristina-soriano.webp' },
      { name: 'Maymarie F. Sumera', image: 'students/maymarie-sumera.webp' },
      { name: 'Ma. Eloisa M. Tapang', image: 'students/eloisa-tapang.webp' },
      { name: 'Grace Patricia A. Tayag', image: 'students/grace-tayag.webp' },
      { name: 'Mary Rose G. Uy', image: 'students/mary-uy.webp' },
      { name: 'Marietta C. Vicencio', image: 'students/marietta-vicencio.webp' },
      { name: 'Mary Jane Villarica', image: 'students/mary-villarica.webp' },
      { name: 'Marjorie U. Villacruz', image: 'students/marjorie-villacruz.webp' },
      { name: 'Michelle Marie C. Vinzons', image: 'students/michelle-vinzons.webp' },
      { name: 'Ma. Isabel Loreto R. Zuela', image: 'students/isabel-zuela.webp' }
    ],
    other: [
    ]
  },
  {
    id: '424BG',
    title: '424-BG',
    adviser: { name: 'Danilo Concepcion', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Myra C. Laforteza', shortName: 'Myra Laforteza' },
      { role: 'Vice-President', name: 'Michael P. Mutuc', shortName: 'Michael Mutuc' },
      { role: 'Secretary', name: 'Salmer P. Espinosa', shortName: 'Salmer Espinosa' },
      { role: 'Treasurer', name: 'Mary Gretchen Martinez', shortName: 'Gretchen Martinez' },
      { role: 'P.R.O.', name: 'Michelle Macapagal', shortName: 'Michelle Macapagal' },
      { role: 'Sgt. at Arms', name: 'Ramil B. Tuason', shortName: 'Ramil Tuason' }
    ],
    students: [
      { name: 'Alexandrius A. Alba', image: 'students/alexandrius-alba.webp' },
      { name: 'Rommel L. Alcantara', image: 'students/rommel-alcantara.webp' },
      { name: 'Jeffrey C. Dollente', image: 'students/jeffrey-dollente.webp' },
      { name: 'Tegie F. Dorado', image: 'students/tegie-dorado.webp' },
      { name: 'Salmer P. Espinosa', image: 'students/salmer-espinosa.webp' },
      { name: 'Ysmael F. Fernandez', image: 'students/ysmael-fernandez.webp' },
      { name: 'Gerardo S. Halili', image: 'students/gerardo-halili.webp' },
      { name: 'Joselito Q. De Leon', image: 'students/joselito-deleon.webp' },
      { name: 'Mar August B. Leoncio', image: 'students/mar-leoncio.webp' },
      { name: 'Angelo E. Llorando', image: 'students/angelo-llorando.webp' },
      { name: 'Edwin S. Manalastas', image: 'students/edwin-manalastas.webp' },
      { name: 'Bernardino C. Masilungan', image: 'students/bernardino-masilungan.webp' },
      { name: 'Julius Rendell L. Merencillo', image: 'students/julius-merencillo.webp' },
      { name: 'Brendan D. Morfe', image: 'students/brendan-morfe.webp' },
      { name: 'Michael P. Mutuc', image: 'students/michael-mutuc.webp' },
      { name: 'Edmon M. Naniong', image: 'students/edmon-naniong.webp' },
      { name: 'Arnulfo L. Necio', image: 'students/arnulfo-necio.webp' },
      { name: 'Antonio B. Pablo Jr.', image: 'students/antonio-pablo.webp' },
      { name: 'Jonathan Palanca', image: 'students/jonathan-palanca.webp' },
      { name: 'Alvin M. Pangilinan', image: 'students/alvin-pangilinan.webp' },
      { name: 'Salvador M. Peralta Jr.', image: 'students/salvador-peralta.webp' },
      { name: 'Eric D. J. Picar', image: 'students/eric-picar.webp' },
      { name: 'Norberto L. Punsalan', image: 'students/norberto-punsalan.webp' },
      { name: 'Jose Roderick T. Quintos', image: 'students/jose-quintos.webp' },
      { name: 'Peter T. Ramos', image: 'students/peter-ramos.webp' },
      { name: 'Addison C. Raymundo', image: 'students/addison-raymundo.webp' },
      { name: 'Adrian L. Reyes', image: 'students/adrian-reyes.webp' },
      { name: 'Leodegario C. De Los Reyes', image: 'students/leodegario-delosreyes.webp' },
      { name: 'Joseph Roy L. Sales', image: 'students/joseph-sales.webp' },
      { name: 'John Alross N. Salvosa', image: 'students/john-salvosa.webp' },
      { name: 'Frederick C. Solis', image: 'students/frederick-solis.webp' },
      { name: 'Leandro Albino B. Tibia', image: 'students/leandro-tibia.webp' },
      { name: 'Rolando D. Tolentino', image: 'students/rolando-tolentino.webp' },
      { name: 'Virgilio L. Tolentino', image: 'students/virgilio-tolentino.webp' },
      { name: 'Ramil B. Tuason', image: 'students/ramil-tuason.webp' },
      { name: 'Jose Antonio Y. Villar', image: 'students/jose-villar.webp' },
      { name: 'Jackson V. Yabut', image: 'students/jackson-yabut.webp' },
      { name: 'Ma. Imaculada T. Jovellanos', image: 'students/imaculada-jovellanos.webp' },
      { name: 'Lorna U. Lacsamana', image: 'students/lorna-lacsamana.webp' },
      { name: 'Myra C. Laforteza', image: 'students/myra-laforteza.webp' },
      { name: 'Ma. Theresa L. Largoza', image: 'students/theresa-largoza.webp' },
      { name: 'Rosemarie Fe A. De Leon', image: 'students/rosemarie-deleon.webp' },
      { name: 'Michelle Macapagal', image: 'students/michelle-macapagal.webp' },
      { name: 'Mary Gretchen Martinez', image: 'students/mary-martinez.webp' },
      { name: 'Catherine R. Miranda', image: 'students/catherine-miranda.webp' },
      { name: 'Jovie Anne Munar', image: 'students/jovie-munar.webp' },
      { name: 'Alma R. Pantaleon', image: 'students/alma-pantaleon.webp' },
      { name: 'Mylene C. Dela Peña', image: 'students/mylene-delapena.webp' },
      { name: 'Annalizza A. Reynon', image: 'students/annalizza-reynon.webp' },
      { name: 'Rhodora D. L. Roque', image: 'students/rhodora-roque.webp' },
      { name: 'Rowena P. Del Rosario', image: 'students/rowena-delrosario.webp' },
      { name: 'Maria Roselle E. Salac', image: 'students/maria-salac.webp' },
      { name: 'Linette R. Salvador', image: 'students/linette-salvador.webp' },
      { name: 'Daisylene M. Santos', image: 'students/daisylene-santos.webp' }
    ],
    other: [
        { title: 'Boys and girls!', image: 'other/classroom.webp' },
    ]
  },
  {
    id: '415G',
    title: '415-G',
    adviser: { name: 'Eden B. Tolentino', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Eden Songco', shortName: 'Eden Songco' },
      { role: 'Vice-President', name: 'Rizza P. Cosay', shortName: 'Rizza Cosay' },
      { role: 'Secretary', name: 'Ermelina I. Espiritu', shortName: 'Ermelina Espiritu' },
      { role: 'Treasurer', name: 'Geraldine M. Morales', shortName: 'Geraldine Morales' },
      { role: 'P.R.O.', name: 'Eileen V. Lim', shortName: 'Eileen Lim' },
      { role: 'Sgt. at Arms', name: 'Catherine C. Cristobal', shortName: 'Catherine Cristobal' }
    ],
    students: [
      { name: 'Ellen A. Abrigonde', image: 'students/ellen-abrigonde.webp' },
      { name: 'Rowena M. Afante', image: 'students/rowena-afante.webp' },
      { name: 'Resurreccion P. Aliento', image: 'students/resurreccion-aliento.webp' },
      { name: 'Christine Carizza T. Arceo', image: 'students/christine-arceo.webp' },
      { name: 'Marie Aurina S. Arsenio', image: 'students/marie-arsenio.webp' },
      { name: 'Vina G. Bagus', image: 'students/vina-bagus.webp' },
      { name: 'Aurora O. Bautista', image: 'students/aurora-bautista.webp' },
      { name: 'Adelaine S. Beltran', image: 'students/adelaine-beltran.webp' },
      { name: 'Dinnah A. Constantino', image: 'students/dinnah-constantino.webp' },
      { name: 'Rizza P. Cosay', image: 'students/rizza-cosay.webp' },
      { name: 'Cherrie P. Crisostomo', image: 'students/cherrie-crisostomo.webp' },
      { name: 'Catherine C. Cristobal', image: 'students/catherine-cristobal.webp' },
      { name: 'Yasmin E. Dispo', image: 'students/yasmin-dispo.webp' },
      { name: 'Lavinia A. Eclarinal', image: 'students/lavinia-eclarinal.webp' },
      { name: 'Ermelina I. Espiritu', image: 'students/ermelina-espiritu.webp' },
      { name: 'Marivic O. Eugenio', image: 'students/marivic-eugenio.webp' },
      { name: 'Cecilia M. Ferros', image: 'students/cecilia-ferros.webp' },
      { name: 'Elena P. Foronda', image: 'students/elena-foronda.webp' },
      { name: 'Ma. Cristina S. Fortuno', image: 'students/cristina-fortuno.webp' },
      { name: 'Grace E. Gabriel', image: 'students/grace-gabriel.webp' },
      { name: 'Leah Z. Gemora', image: 'students/leah-gemora.webp' },
      { name: 'Liza G. Guanlao', image: 'students/liza-guanlao.webp' },
      { name: 'Luisa L. Labro', image: 'students/luisa-labro.webp' },
      { name: 'Lailani N. Lanot', image: 'students/lailani-lanot.webp' },
      { name: 'Bernadette P. Lazatin', image: 'students/bernadette-lazatin.webp' },
      { name: 'Eileen V. Lim', image: 'students/eileen-lim.webp' },
      { name: 'Jemina Agnes B. Mania', image: 'students/jemina-mania.webp' },
      { name: 'Ma. Theresa M. Mardoquio', image: 'students/theresa-mardoquio.webp' },
      { name: 'Anne Marie M. Mendoza', image: 'students/anne-mendoza.webp' },
      { name: 'Geraldine M. Morales', image: 'students/geraldine-morales.webp' },
      { name: 'Jocelyne B. Obligar', image: 'students/jocelyne-obligar.webp' },
      { name: 'Ma. Cristina H. Orbeta', image: 'students/cristina-orbeta.webp' },
      { name: 'Greta V. Pacheco', image: 'students/greta-pacheco.webp' },
      { name: 'Wennylyn A. Panaligan', image: 'students/wennylyn-panaligan.webp' },
      { name: 'Amylene C. Pormento', image: 'students/amylene-pormento.webp' },
      { name: 'Primerose P. Punzal', image: 'students/primerose-punzal.webp' },
      { name: 'Jesusa R. Ramos', image: 'students/jesusa-ramos.webp' },
      { name: 'Marie Antonette P. Reyes', image: 'students/marie-reyes.webp' },
      { name: 'Jennifer T. Roque', image: 'students/jennifer-roque.webp' },
      { name: 'Sahlee A. Sabayday', image: 'students/sahlee-sabayday.webp' },
      { name: 'Olivia T. San Buenaventura', image: 'students/olivia-sanbuenaventura.webp' },
      { name: 'Consolacion C. Sebastian', image: 'students/consolacion-sebastian.webp' },
      { name: 'Marie Melody D. Serina', image: 'students/marie-serina.webp' },
      { name: 'Eden Songco', image: 'students/eden-songco.webp' },
      { name: 'Lucia Ester A. Susa', image: 'students/lucia-susa.webp' },
      { name: 'Ma. Liezl S. Tacazon', image: 'students/liezl-tacazon.webp' },
      { name: 'Rhona F. Vesagas', image: 'students/rhona-vesagas.webp' },
      { name: 'Christine E. Villanueva', image: 'students/christine-villanueva.webp' },
      { name: 'Esperanza P. Villanueva', image: 'students/esperanza-villanueva.webp' },
      { name: 'Mariel Angelica G. Ynaya', image: 'students/mariel-ynaya.webp' }
    ],
    other: [
        { title: 'Down-to-earth girls', image: 'other/classroom.webp' },
    ]
  },
  {
    id: '415B',
    title: '415-B',
    adviser: { name: 'Fr. Bonifacio Solis, O.P.', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Edwin P. Santiago', shortName: 'Edwin Santiago' },
      { role: 'Vice-President', name: 'Bryan Carl G. Collado', shortName: 'Bryan Collado' },
      { role: 'Secretary', name: 'Frederick Cayetano', shortName: 'Frederick Cayetano' },
      { role: 'Treasurer', name: 'Manchi J. Melencio', shortName: 'Manchi Melencio' },
      { role: 'P.R.O.', name: 'Flerido N. Quiambao', shortName: 'Flerido Quiambao' },
      { role: 'Sgt. at Arms', name: 'Joseph Efigenio A. Dela Rosa', shortName: 'Joseph Dela Rosa' }
    ],
    students: [
      { name: 'Gregorio C. Acuin Jr.', image: 'students/gregorio-acuin.webp' },
      { name: 'Arnold A. Alacar', image: 'students/arnold-alacar.webp' },
      { name: 'Allen Arugay', image: 'students/allen-arugay.webp' },
      { name: 'Noel S. Avila', image: 'students/noel-avila.webp' },
      { name: 'Rafael A. Aviles', image: 'students/rafael-aviles.webp' },
      { name: 'Carmelo A. Aviso', image: 'students/carmelo-aviso.webp' },
      { name: 'Jerrold A. Bano', image: 'students/jerrold-bano.webp' },
      { name: 'Edwin S. J. Baris', image: 'students/edwin-baris.webp' },
      { name: 'Dan Vincent Barros', image: 'students/dan-barros.webp' },
      { name: 'Anthony Bonsoi', image: 'students/anthony-bonsoi.webp' },
      { name: 'Frederick Buhat', image: 'students/frederick-buhat.webp' },
      { name: 'Renato D. Burdeos', image: 'students/renato-burdeos.webp' },
      { name: 'Rex V. Calupang', image: 'students/rex-calupang.webp' },
      { name: 'Erickson J. J. Capulong', image: 'students/erickson-capulong.webp' },
      { name: 'Joel M. De Castro', image: 'students/joel-decastro.webp' },
      { name: 'Eric Michael C. Cayahan', image: 'students/eric-cayahan.webp' },
      { name: 'Frederick Cayetano', image: 'students/frederick-cayetano.webp' },
      { name: 'Bryan Carl G. Collado', image: 'students/bryan-collado.webp' },
      { name: 'David C. Dacio', image: 'students/david-dacio.webp' },
      { name: 'Jon-Jon A. Dizon', image: 'students/jon-dizon.webp' },
      { name: 'Ranulfo O. Espera', image: 'students/ranulfo-espera.webp' },
      { name: 'Fernandy M. Fernandez', image: 'students/fernandy-fernandez.webp' },
      { name: 'Tristan J. Fernandez', image: 'students/tristan-fernandez.webp' },
      { name: 'Wilson Joy Fernandez', image: 'students/wilson-fernandez.webp' },
      { name: 'Thomas S. Francisco', image: 'students/thomas-francisco.webp' },
      { name: 'Roberto Hontiveros', image: 'students/roberto-hontiveros.webp' },
      { name: 'Michael F. Lara', image: 'students/michael-lara.webp' },
      { name: 'Jonathan F. Layug', image: 'students/jonathan-layug.webp' },
      { name: 'Jason P. Legaspi', image: 'students/jason-legaspi.webp' },
      { name: 'Felixberto M. Maneza Jr.', image: 'students/felixberto-maneza.webp' },
      { name: 'Michael E. Matias', image: 'students/michael-matias.webp' },
      { name: 'Manchi J. Melencio', image: 'students/manchi-melencio.webp' },
      { name: 'Darwin C. Mendoza', image: 'students/darwin-mendoza.webp' },
      { name: 'Albert Gabriel B. De Mesa', image: 'students/albert-demesa.webp' },
      { name: 'Isagani D. Miguel', image: 'students/isagani-miguel.webp' },
      { name: 'Joseph Hanna D. Mitre', image: 'students/joseph-mitre.webp' },
      { name: 'Michael S. Pagbilao', image: 'students/michael-pagbilao.webp' },
      { name: 'Viktor R. Peñas', image: 'students/viktor-penas.webp' },
      { name: 'Flerido N. Quiambao', image: 'students/flerido-quiambao.webp' },
      { name: 'Joseph Efigenio A. Dela Rosa', image: 'students/joseph-delarosa.webp' },
      { name: 'Dennis C. Sabile', image: 'students/dennis-sabile.webp' },
      { name: 'Ted Edward V. Sadio', image: 'students/ted-sadio.webp' },
      { name: 'Edwin P. Santiago', image: 'students/edwin-santiago.webp' },
      { name: 'Rommel I. Solitario', image: 'students/rommel-solitario.webp' },
      { name: 'Leonardo L. Sto. Domingo', image: 'students/leonardo-stodomingo.webp' },
      { name: 'Emmanuel V. Tallador', image: 'students/emmanuel-tallador.webp' },
      { name: 'Hector A. Tan', image: 'students/hector-tan.webp' },
      { name: 'Florante Tolentino', image: 'students/florante-tolentino.webp' },
      { name: 'Ronald Tonido', image: 'students/ronald-tonido.webp' },
      { name: 'Rolando J. De Torres', image: 'students/rolando-detorres.webp' },
      { name: 'Vern V. Veron', image: 'students/vern-veron.webp' },
      { name: 'Joseph Viray', image: 'students/joseph-viray.webp' }
    ],
    other: [
        { title: 'Pain in the neck', image: 'other/classroom.webp' },
    ]
  }
];
