export interface Officer {
  role: string;
  name: string;
  shortName: string;
}

export interface Student {
  name: string;
  image: string;
}

export interface OtherPhoto {
  title: string;
  image: string;
}

export interface SectionData {
  id: string;
  title: string;
  adviser: {
    name: string;
    image: string;
  };
  cover: {
    classPhoto: string;
  };
  officers: Officer[];
  students: Student[];
  other: OtherPhoto[];
}

export const sections: SectionData[] = [
  {
    id: '421G',
    title: '421-G',
    adviser: { name: 'Mrs. Norina Gapasin', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Angie M. Arguna', shortName: 'Angie Arguna' },
      { role: 'Vice-President', name: 'Ma. Cecilia A. Nalagan', shortName: 'Cecilia Nalagan' },
      { role: 'Secretary', name: 'Marie Charlyn O. Exaltado', shortName: 'Marie Charlyn Exaltado' },
      { role: 'Treasurer', name: 'Vivian S. De Guzman', shortName: 'Vivian De Guzman' },
      { role: 'P.R.O.', name: 'Gladys R. Guitan', shortName: 'Gladys Guitan' },
      { role: 'Sgt. at Arms', name: 'Heidi S. Palaca', shortName: 'Heidi Palaca' }
    ],
    students: [
      { name: 'Grace Ann O. Alano', image: 'students/grace-alano.webp' },
      { name: 'Noemi Ruth G. Aldez', image: 'students/noemi-aldez.webp' },
      { name: 'Andrea Gladys Paz P. Aquino', image: 'students/andrea-aquino.webp' },
      { name: 'Angie M. Arguna', image: 'students/angie-arguna.webp' },
      { name: 'Leilani D. Aspeli', image: 'students/leilani-aspeli.webp' },
      { name: 'Myrna F. Atienza', image: 'students/myrna-atienza.webp' },
      { name: 'Elayda Clara Marie T. Beltran', image: 'students/elayda-beltran.webp' },
      { name: 'Florence F. Buerano', image: 'students/florence-buerano.webp' },
      { name: 'Carmela O. Castro', image: 'students/carmela-castro.webp' },
      { name: 'Shirin Marie N. Elio', image: 'students/shirin-elio.webp' },
      { name: 'Ma. Teresita M. Esguerra', image: 'students/teresita-esguerra.webp' },
      { name: 'Cecile N. Espocia', image: 'students/cecile-espocia.webp' },
      { name: 'Marie Charlyn O. Exaltado', image: 'students/marie-exaltado.webp' },
      { name: 'Ressie R. Framil', image: 'students/ressie-framil.webp' },
      { name: 'Vilma T. Gatchalian', image: 'students/vilma-gatchalian.webp' },
      { name: 'Gladys R. Guitan', image: 'students/gladys-guitan.webp' },
      { name: 'Vivian S. De Guzman', image: 'students/vivian-deguzman.webp' },
      { name: 'Ma. Larissa M. Halili', image: 'students/larissa-halili.webp' },
      { name: 'Ma. Cecilia V. Interior', image: 'students/cecilia-interior.webp' },
      { name: 'Ma. Rosario I. Jimenez', image: 'students/rosario-jimenez.webp' },
      { name: 'Katherine T. Justiniano', image: 'students/katherine-justiniano.webp' },
      { name: 'Jolianne Q. Lan', image: 'students/jolianne-lan.webp' },
      { name: 'Candice Twinkle S. Laureta', image: 'students/candice-laureta.webp' },
      { name: 'Josephine P. Linsangan', image: 'students/josephine-linsangan.webp' },
      { name: 'Ma. Viviane P. Magno', image: 'students/viviane-magno.webp' },
      { name: 'Noemi B. Misicampo Jra.', image: 'students/noemi-misicampo.webp' },
      { name: 'Regina Ma. Auxiliadora Mendigoria', image: 'students/regina-mendigoria.webp' },
      { name: 'Naomi G. Milay', image: 'students/naomi-milay.webp' },
      { name: 'Ma. Cecilia A. Nalagan', image: 'students/cecilia-nalagan.webp' },
      { name: 'Ezelyn L. Navarro', image: 'students/ezelyn-navarro.webp' },
      { name: 'Rosalinda G. Ong', image: 'students/rosalinda-ong.webp' },
      { name: 'Ma. Alicia F. Paggabao', image: 'students/alicia-paggabao.webp' },
      { name: 'Heidi S. Palaca', image: 'students/heidi-palaca.webp' },
      { name: 'Connie H. Paris', image: 'students/connie-paris.webp' },
      { name: 'Rowena V. Perez', image: 'students/rowena-perez.webp' },
      { name: 'Mary Ann M. Quilala', image: 'students/maryann-quilala.webp' },
      { name: 'Ma. Pacita B. Rivera', image: 'students/pacita-rivera.webp' },
      { name: 'Nancy Grace A. Robles', image: 'students/nancy-robles.webp' },
      { name: 'Violeta A. San Juan', image: 'students/violeta-sanjuan.webp' },
      { name: 'Ma. Cristina F. Santos', image: 'students/cristina-santos.webp' },
      { name: 'Aimee B. Sarmiento', image: 'students/aimee-sarmiento.webp' },
      { name: 'Ma. Cecilia M. Soller', image: 'students/cecilia-soller.webp' },
      { name: 'Kathrina V. Suarez', image: 'students/kathrina-suarez.webp' },
      { name: 'Mitus L. Sumcad', image: 'students/mitus-sumcad.webp' },
      { name: 'Ma. Virginia G. Tigno', image: 'students/virginia-tigno.webp' },
      { name: 'Shirley G. Tismo', image: 'students/shirley-tismo.webp' },
      { name: 'Rachel M. Tolosa', image: 'students/rachel-tolosa.webp' },
      { name: 'Purificacion N. Tongol', image: 'students/purificacion-tongol.webp' },
      { name: 'Veronica C. Umali', image: 'students/veronica-umali.webp' },
      { name: 'Marites B. Uy', image: 'students/marites-uy.webp' },
      { name: 'Mariechit Gloria S. De Vera', image: 'students/mariechit-devera.webp' },
      { name: 'Marilou S. De Vera', image: 'students/marilou-devera.webp' },
      { name: 'Shirley C. Yu', image: 'students/shirley-yu.webp' }
    ],
    other: [
      { title: 'Mga pa-cute', image: 'other/classroom.webp' },
    ]
  },
  {
    id: '421B',
    title: '421-B',
    adviser: { name: 'Mrs. Cipriana V. Yu', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'John Ulysses D. Abu', shortName: 'John Abu' },
      { role: 'Vice-President', name: 'Lyndon B. Denia', shortName: 'Lyndon Denia' },
      { role: 'Secretary', name: 'Ferdinand C. Bundang', shortName: 'Ferdinand Bundang' },
      { role: 'Treasurer', name: 'Augusto B. Cruz Jr.', shortName: 'Augusto Cruz Jr.' },
      { role: 'P.R.O.', name: 'Reynaldo C. Idano', shortName: 'Reynaldo Idano' },
      { role: 'Sgt. at Arms', name: 'Neil C. Tan', shortName: 'Neil Tan' }
    ],
    students: [
      { name: 'John Ulysses D. Abu', image: 'students/john-abu.webp' },
      { name: 'Edgardo A. Agbada', image: 'students/edgardo-agbada.webp' },
      { name: 'Jose Ma. G. Alarilla', image: 'students/jose-alarilla.webp' },
      { name: 'Enrique G. Armentia', image: 'students/enrique-armentia.webp' },
      { name: 'William A. Asuncion Jr.', image: 'students/william-asuncion.webp' },
      { name: 'Raymond P. Azul', image: 'students/raymond-azul.webp' },
      { name: 'Robert B. Belleza', image: 'students/robert-belleza.webp' },
      { name: 'Gary Stephen S. Briones', image: 'students/gary-briones.webp' },
      { name: 'Ruben F. Bukas Jr.', image: 'students/ruben-bukas.webp' },
      { name: 'Ferdinand C. Bundang', image: 'students/ferdinand-bundang.webp' },
      { name: 'Reynaldo C. Caladiao', image: 'students/reynaldo-caladiao.webp' },
      { name: 'Ariel C. de Castro', image: 'students/ariel-decastro.webp' },
      { name: 'Kenneth Lee G. de Castro', image: 'students/kenneth-decastro.webp' },
      { name: 'Jeremy C. Chu', image: 'students/jeremy-chu.webp' },
      { name: 'Renante C. Cortez', image: 'students/renante-cortez.webp' },
      { name: 'Hector P. Crisostomo VI', image: 'students/hector-crisostomo.webp' },
      { name: 'Augusto B. Cruz Jr.', image: 'students/augusto-cruz.webp' },
      { name: 'Jesus Romano S. Datu', image: 'students/jesus-datu.webp' },
      { name: 'Lyndon B. Denia', image: 'students/lyndon-denia.webp' },
      { name: 'Ronald Reagan S. Domingo', image: 'students/ronald-domingo.webp' },
      { name: 'John Kerwin G. Du', image: 'students/john-du.webp' },
      { name: 'Henry D. Dumaoal', image: 'students/henry-dumaoal.webp' },
      { name: 'Jericho G. Estrella', image: 'students/jericho-estrella.webp' },
      { name: 'Dennis B. Hatoc', image: 'students/dennis-hatoc.webp' },
      { name: 'Enrique R. Hipolito', image: 'students/enrique-hipolito.webp' },
      { name: 'Reynaldo C. Idano', image: 'students/reynaldo-idano.webp' },
      { name: 'Jonathan C. Javier', image: 'students/jonathan-javier.webp' },
      { name: 'Ronald C. Jimenez', image: 'students/ronald-jimenez.webp' },
      { name: 'Amor P. Lauro', image: 'students/amor-lauro.webp' },
      { name: 'Paul Anthony P. Mandal', image: 'students/paul-mandal.webp' },
      { name: 'Peter P. Mandal', image: 'students/peter-mandal.webp' },
      { name: 'Ronaldo O. Marano', image: 'students/ronaldo-marano.webp' },
      { name: 'John Paul T. Marbella', image: 'students/john-marbella.webp' },
      { name: 'Ace Sterling R. Medina', image: 'students/ace-medina.webp' },
      { name: 'Michael Conrad D. Mendoza', image: 'students/michael-mendoza.webp' },
      { name: 'Julius Pichito T. Minas', image: 'students/julius-minas.webp' },
      { name: 'Stephen Thomas S. Misa', image: 'students/stephen-misa.webp' },
      { name: 'Renato K. Mitra Jr.', image: 'students/renato-mitra.webp' },
      { name: 'Raymond I. Nano', image: 'students/raymond-nano.webp' },
      { name: 'Jesus O. Ocasla', image: 'students/jesus-ocasla.webp' },
      { name: 'Earl R. Perez', image: 'students/earl-perez.webp' },
      { name: 'Maximino S. Picio III', image: 'students/maximino-picio.webp' },
      { name: 'James S. Plaza', image: 'students/james-plaza.webp' },
      { name: 'Rudyard Michael A. Ranjo', image: 'students/rudyard-ranjo.webp' },
      { name: 'Gilbert G. Robles', image: 'students/gilbert-robles.webp' },
      { name: 'Marianito R. Rodrigo', image: 'students/marianito-rodrigo.webp' },
      { name: 'Dennis J. Rotairo', image: 'students/dennis-rotairo.webp' },
      { name: 'Melanio G. Rubio Jr.', image: 'students/melanio-rubio.webp' },
      { name: 'Neil C. Tan', image: 'students/neil-tan.webp' },
      { name: 'Arnold B. Teodoro', image: 'students/arnold-teodoro.webp' },
      { name: 'Randy G. Venezuela', image: 'students/randy-venezuela.webp' },
      { name: 'Anthony Allan D. Villanueva', image: 'students/anthony-villanueva.webp' },
      { name: 'Carlos C. Villarias Jr.', image: 'students/carlos-villarias.webp' }
    ],
    other: [
      { title: 'Nerd paradise', image: 'other/classroom.webp' }
    ]
  },
  {
    id: '422G',
    title: '422-G',
    adviser: { name: 'Mrs. Teresita N. Alves', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Verna T. Miranda', shortName: 'Verna Miranda' },
      { role: 'Vice-President', name: 'Amillie Charito Jewel A. Japa', shortName: 'Amilie Japa' },
      { role: 'Secretary', name: 'Aileen C. Singson', shortName: 'Aileen Singson' },
      { role: 'Treasurer', name: 'Bernadette C. Lopez', shortName: 'Bernadette Lopez' },
      { role: 'P.R.O.', name: 'Brenda Joy O. Poblete', shortName: 'Brenda Poblete' },
      { role: 'Sgt. at Arms', name: 'Miriam O. Santos', shortName: 'Miriam Santos' }
    ],
    students: [
      { name: 'Evarose A. Alvarez', image: 'students/evarose-alvarez.webp' },
      { name: 'Joan T. Apelo', image: 'students/joan-apelo.webp' },
      { name: 'Rowena S. Baguino', image: 'students/rowena-baguino.webp' },
      { name: 'Myra S. Batac', image: 'students/myra-batac.webp' },
      { name: 'Ma. Lilibeth V. Batungbakal', image: 'students/lilibeth-batungbakal.webp' },
      { name: 'Veronica L. Bautista', image: 'students/veronica-bautista.webp' },
      { name: 'Vivienne D. Bautista', image: 'students/vivienne-bautista.webp' },
      { name: 'Janette C. Benemerito', image: 'students/janette-benemerito.webp' },
      { name: 'Angelica C. Bien', image: 'students/angelica-bien.webp' },
      { name: 'Lizza E. Cabarles', image: 'students/lizza-cabarles.webp' },
      { name: 'Anna Cielo Vic B. Canlas', image: 'students/anna-canlas.webp' },
      { name: 'Ma. Theresa P. Carlos', image: 'students/theresa-carlos.webp' },
      { name: 'Ma. Arlene S. Castillo', image: 'students/arlene-castillo.webp' },
      { name: 'Mary Rose C. De Castro', image: 'students/mary-decastro.webp' },
      { name: 'Sheila R. Castro', image: 'students/sheila-castro.webp' },
      { name: 'Sonia J. Cordoviz', image: 'students/sonia-cordoviz.webp' },
      { name: 'Aileen G. Cura', image: 'students/aileen-cura.webp' },
      { name: 'Mary Grace A. Delgado', image: 'students/mary-delgado.webp' },
      { name: 'Theresa Angela K. Dismas', image: 'students/theresa-dismas.webp' },
      { name: 'Anna Bernardita M. Enriquez', image: 'students/anna-enriquez.webp' },
      { name: 'Ma. Millicent C. Esberto', image: 'students/millicent-esberto.webp' },
      { name: 'Romela F. Faeldonia', image: 'students/romela-faeldonia.webp' },
      { name: 'Gina Maria C. Gener', image: 'students/gina-gener.webp' },
      { name: 'Jocelyn S. Gapo', image: 'students/jocelyn-gapo.webp' },
      { name: 'Fatima A. De Gorostiza', image: 'students/fatima-degorostiza.webp' },
      { name: 'Ma. Joan Gualberto', image: 'students/joan-gualberto.webp' },
      { name: 'Carmina Fatima V. De Guzman', image: 'students/carmina-deguzman.webp' },
      { name: 'Amillie Charito Jewel A. Japa', image: 'students/amillie-japa.webp' },
      { name: 'Myra Constancia B. Lachica', image: 'students/myra-lachica.webp' },
      { name: 'Josephine C. Lampa', image: 'students/josephine-lampa.webp' },
      { name: 'Bernadette C. Lopez', image: 'students/bernadette-lopez.webp' },
      { name: 'Marilou J. Mendoza', image: 'students/marilou-mendoza.webp' },
      { name: 'Jennifer C. Meneses', image: 'students/jennifer-meneses.webp' },
      { name: 'Verna T. Miranda', image: 'students/verna-miranda.webp' },
      { name: 'Janet C. Pineda', image: 'students/janet-pineda.webp' },
      { name: 'Brenda Joy O. Poblete', image: 'students/brenda-poblete.webp' },
      { name: 'Gloria D. Ramos', image: 'students/gloria-ramos.webp' },
      { name: 'Anne Michelle P. Reyes', image: 'students/anne-reyes.webp' },
      { name: 'Marisa P. De Los Reyes', image: 'students/marisa-delosreyes.webp' },
      { name: 'Rosario C. Sandoval', image: 'students/rosario-sandoval.webp' },
      { name: 'Ma. Cristina M. Santos', image: 'students/cristina-santos.webp' },
      { name: 'Miriam O. Santos', image: 'students/miriam-santos.webp' },
      { name: 'Ma. Nereza B. Santuyo', image: 'students/nereza-santuyo.webp' },
      { name: 'Ma. Theresa S. Sena', image: 'students/theresa-sena.webp' },
      { name: 'Aileen C. Singson', image: 'students/aileen-singson.webp' },
      { name: 'Liza D. Solis', image: 'students/liza-solis.webp' },
      { name: 'Anna Mae Tan', image: 'students/anna-tan.webp' },
      { name: 'Maribeth A. Tan', image: 'students/maribeth-tan.webp' },
      { name: 'Anita Flordeliza I. Tango', image: 'students/anita-tango.webp' },
      { name: 'Lorelie B. Tiopes', image: 'students/lorelie-tiopes.webp' },
      { name: 'Melinda B. Tolentino', image: 'students/melinda-tolentino.webp' },
      { name: 'Mae Lahnee A. Unite', image: 'students/mae-unite.webp' },
      { name: 'Ma. Jennifer N. Vidal', image: 'students/jennifer-vidal.webp' },
      { name: 'Marie Abegail P. Villadolid', image: 'students/marie-villadolid.webp' },
      { name: 'Ma. Jennifer S. Villanueva', image: 'students/jennifer-villanueva.webp' }
    ],
    other: [      
    ]
  },
  {
    id: '422B',
    title: '422-B',
    adviser: { name: 'Ms. Teresita Y. Santos', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Garrick Van V. Alumisin', shortName: 'Garrick Alumisin' },
      { role: 'Vice-President', name: 'Robert S. Jusay', shortName: 'Robert Jusay' },
      { role: 'Secretary', name: 'Gavini C. Pancho', shortName: 'Gavini Pancho' },
      { role: 'Treasurer', name: 'Roberto I. Belda', shortName: 'Roberto Belda' },
      { role: 'P.R.O.', name: 'Neil John V. Briones', shortName: 'Neil Briones' },
      { role: 'Sgt. at Arms', name: 'Cesar V. Dalde Jr.', shortName: 'Cesar Dalde' }
    ],
    students: [
      { name: 'Geoffrey F. Abello', image: 'students/geoffrey-abello.webp' },
      { name: 'Marcelino J. Alejo Jr.', image: 'students/marcelino-alejo.webp' },
      { name: 'Garrick Van V. Alumisin', image: 'students/garrick-alumisin.webp' },
      { name: 'Bernabe Barr U. Ambrosio', image: 'students/bernabe-ambrosio.webp' },
      { name: 'Gilbert C. Ang', image: 'students/gilbert-ang.webp' },
      { name: 'Edwin I. Antonio', image: 'students/edwin-antonio.webp' },
      { name: 'Rommel E. Argenal', image: 'students/rommel-argenal.webp' },
      { name: 'Luisito D. Articulo', image: 'students/luisito-articulo.webp' },
      { name: 'Zeus R. Balagtas', image: 'students/zeus-balagtas.webp' },
      { name: 'Marlon R. Baltazar', image: 'students/marlon-baltazar.webp' },
      { name: 'Ariel G. Bartilet', image: 'students/ariel-bartilet.webp' },
      { name: 'Ramil D. Bataller', image: 'students/ramil-bataller.webp' },
      { name: 'Roberto I. Belda', image: 'students/roberto-belda.webp' },
      { name: 'Neil John V. Briones', image: 'students/neil-briones.webp' },
      { name: 'Victor L. Cabochan', image: 'students/victor-cabochan.webp' },
      { name: 'Paul John T. Camiring', image: 'students/paul-camiring.webp' },
      { name: 'Leoberdo S. Cortez', image: 'students/leoberdo-cortez.webp' },
      { name: 'Adonis P. Cruz', image: 'students/adonis-cruz.webp' },
      { name: 'Cesar V. Dalde Jr.', image: 'students/cesar-dalde.webp' },
      { name: 'Abraham B. Diaz', image: 'students/abraham-diaz.webp' },
      { name: 'Danilo C. Eulogio', image: 'students/danilo-eulogio.webp' },
      { name: 'Emmanuel C. Feliciano', image: 'students/emmanuel-feliciano.webp' },
      { name: 'Manuel Erwin O. Felipe', image: 'students/manuel-felipe.webp' },
      { name: 'Jaime Victor L. Gabriel', image: 'students/jaime-gabriel.webp' },
      { name: 'Dominic E. Javier', image: 'students/dominic-javier.webp' },
      { name: 'Robert Agustin A. De Jesus Jr.', image: 'students/robert-dejesus.webp' },
      { name: 'Robert S. Jusay', image: 'students/robert-jusay.webp' },
      { name: 'Alvin N. De Leon', image: 'students/alvin-deleon.webp' },
      { name: 'Ramil M. Mirando', image: 'students/ramil-mirando.webp' },
      { name: 'Sidney D. Munji', image: 'students/sidney-munji.webp' },
      { name: 'Manuel M. Oliveros', image: 'students/manuel-oliveros.webp' },
      { name: 'Dexter V. Pacheco', image: 'students/dexter-pacheco.webp' },
      { name: 'Pancrasio D. Pahilan', image: 'students/pancrasio-pahilan.webp' },
      { name: 'Alvin P. Palamos', image: 'students/alvin-palamos.webp' },
      { name: 'Gavini C. Pancho', image: 'students/gavini-pancho.webp' },
      { name: 'Andres Edgar R. Perez', image: 'students/andres-perez.webp' },
      { name: 'Jose Angelo S. Petelo', image: 'students/jose-petelo.webp' },
      { name: 'Miguel H. Podolig', image: 'students/miguel-podolig.webp' },
      { name: 'Primo L. Prado', image: 'students/primo-prado.webp' },
      { name: 'Michael Angelo A. Raymundo', image: 'students/michael-raymundo.webp' },
      { name: 'Carlito M. Redaja', image: 'students/carlito-redaja.webp' },
      { name: 'Roderick D. Reyes', image: 'students/roderick-reyes.webp' },
      { name: 'Severino T. Salaguinto Jr.', image: 'students/severino-salaguinto.webp' },
      { name: 'Hector Joseph E. Samson', image: 'students/hector-samson.webp' },
      { name: 'Eric F. Santos', image: 'students/eric-santos.webp' },
      { name: 'Menardo G. Soliven', image: 'students/menardo-soliven.webp' },
      { name: 'Luisito G. Tirados', image: 'students/luisito-tirados.webp' },
      { name: 'Alexander R. Torres Jr.', image: 'students/alexander-torres.webp' },
      { name: 'Alexander D. Valmeo', image: 'students/alexander-valmeo.webp' },
      { name: 'Rogelio Velicaria', image: 'students/rogelio-velicaria.webp' },
      { name: 'Edgar R. Ventanilla', image: 'students/edgar-ventanilla.webp' },
      { name: 'Reginaldo S. Villanueva', image: 'students/reginaldo-villanueva.webp' },
      { name: 'Byron M. Villegas', image: 'students/byron-villegas.webp' },
      { name: 'Florito L. Yalung', image: 'students/florito-yalung.webp' },
      { name: 'Albert Q. Yamson III', image: 'students/albert-yamson.webp' }
    ],
    other: []
  },
  {
    id: '423G',
    title: '423-G',
    adviser: { name: 'Mrs. Belinda N. Gallamos', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Jocelyn C. Hechanova', shortName: 'Jocelyn Hechanova' },
      { role: 'Vice-President', name: 'Raquel N. Magistrado', shortName: 'Raquel Magistrado' },
      { role: 'Secretary', name: 'Maria Angelica M. Rena', shortName: 'Angelica Rena' },
      { role: 'Treasurer', name: 'Maria Joy V. Osea', shortName: 'Joy Osea' },
      { role: 'P.R.O.', name: 'Leila H. Palma', shortName: 'Leila Palma' },
      { role: 'Sgt. at Arms', name: 'Jonathan G. Baltazar', shortName: 'Jonathan Baltazar' }
    ],
    students: [
      { name: 'Maria Divina A. Alvarado', image: 'students/maria-alvarado.webp' },
      { name: 'Carolina G. Artates', image: 'students/carolina-artates.webp' },
      { name: 'Maria Angelita A. Baisa', image: 'students/maria-baisa.webp' },
      { name: 'Jonathan G. Baltazar', image: 'students/jonathan-baltazar.webp' },
      { name: 'Marissa C. Bautista', image: 'students/marissa-bautista.webp' },
      { name: 'Melanie M. Bayro', image: 'students/melanie-bayro.webp' },
      { name: 'Eliza F. Cabantig', image: 'students/eliza-cabantig.webp' },
      { name: 'Elizabeth L. Caparas', image: 'students/elizabeth-caparas.webp' },
      { name: 'Mitos R. Cayanan', image: 'students/mitos-cayanan.webp' },
      { name: 'Miriam S. Concepcion', image: 'students/miriam-concepcion.webp' },
      { name: 'Agnes M. Crelencia', image: 'students/agnes-crelencia.webp' },
      { name: 'Criselda L. Cruz', image: 'students/criselda-cruz.webp' },
      { name: 'Marinette Ann R. Cruz', image: 'students/marinette-cruz.webp' },
      { name: 'Corinne Y. Cubias', image: 'students/corinne-cubias.webp' },
      { name: 'Maria Vina S. Dinglasan', image: 'students/maria-dinglasan.webp' },
      { name: 'Perla Florida L. Dirige', image: 'students/perla-dirige.webp' },
      { name: 'Armida C. Estanislao', image: 'students/armida-estanislao.webp' },
      { name: 'Mary Ann V. Esteban', image: 'students/mary-esteban.webp' },
      { name: 'Jocelyn C. Hechanova', image: 'students/jocelyn-hechanova.webp' },
      { name: 'Raquel N. Magistrado', image: 'students/raquel-magistrado.webp' },
      { name: 'Nannette G. Manalese', image: 'students/nannette-manalese.webp' },
      { name: 'Maria Josefina M. Manalo', image: 'students/maria-manalo.webp' },
      { name: 'Elyn T. Mangrobang', image: 'students/elyn-mangrobang.webp' },
      { name: 'Lyn Leni L. Mendoza', image: 'students/lyn-mendoza.webp' },
      { name: 'Molly Ann S. Mendoza', image: 'students/molly-mendoza.webp' },
      { name: 'Minabel Melchora B. Mercado', image: 'students/minabel-mercado.webp' },
      { name: 'Cesarina B. Minas', image: 'students/cesarina-minas.webp' },
      { name: 'Aileen B. Molina', image: 'students/aileen-molina.webp' },
      { name: 'Annalyn G. Oliveros', image: 'students/annalyn-oliveros.webp' },
      { name: 'Roby Ann Charmagne A. Opena', image: 'students/roby-opena.webp' },
      { name: 'Yvonne M. Orlinda', image: 'students/yvonne-orlinda.webp' },
      { name: 'Maria Joy V. Osea', image: 'students/maria-osea.webp' },
      { name: 'Leila H. Palma', image: 'students/leila-palma.webp' },
      { name: 'Grace B. Panganiban', image: 'students/grace-panganiban.webp' },
      { name: 'Miriam V. Pangilinan', image: 'students/miriam-pangilinan.webp' },
      { name: 'Alma T. Quitangon', image: 'students/alma-quitangon.webp' },
      { name: 'Luisa Trinita S. Ranada', image: 'students/luisa-ranada.webp' },
      { name: 'Maria Angelica M. Rena', image: 'students/maria-rena.webp' },
      { name: 'Anna Lisa D. Rivera', image: 'students/anna-rivera.webp' },
      { name: 'Christine P. Salando', image: 'students/christine-salando.webp' },
      { name: 'Relynn F. Salanguit', image: 'students/relynn-salanguit.webp' },
      { name: 'Mary Claire N. Serra', image: 'students/mary-serra.webp' },
      { name: 'Maria Rosanna S. Sian', image: 'students/maria-sian.webp' },
      { name: 'Jessica Ann M. Silo', image: 'students/jessica-silo.webp' },
      { name: 'Arlene V. Sta. Ines', image: 'students/arlene-staines.webp' },
      { name: 'Marie Phyllis E. Tablada', image: 'students/marie-tablada.webp' },
      { name: 'Mary Beth A. Tan', image: 'students/mary-tan.webp' },
      { name: 'Monica A. Tungol', image: 'students/monica-tungol.webp' },
      { name: 'Lourdes M. Velasco', image: 'students/lourdes-velasco.webp' },
      { name: 'Joanne Fabianne M. Viado', image: 'students/joanne-viado.webp' },
      { name: 'Mary Ann I. Vuelba', image: 'students/mary-vuelba.webp' },
      { name: 'Helen Grace A. Yanca', image: 'students/helen-yanca.webp' },
      { name: 'Janet M. Yasona', image: 'students/janet-yasona.webp' },
      { name: 'Leilanie P. Zaldarriaga', image: 'students/leilanie-zaldarriaga.webp' }
    ],
    other: [      
      { title: 'Nice, sweet, and pretty', image: 'other/classroom.webp' },
    ]
  },
  {
    id: '423B',
    title: '423-B',
    adviser: { name: 'Mr. Alexander Tagaro', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Farley John M. Javier', shortName: 'Farley Javier' },
      { role: 'Vice-President', name: 'Remlee M. Dela Cruz', shortName: 'Remlee Dela Cruz' },
      { role: 'Secretary', name: 'Romeo S. Diaz Jr.', shortName: 'Romeo Diaz Jr.' },
      { role: 'Treasurer', name: 'Von Ferdinand O. Villagarcia', shortName: 'Von Villagarcia' },
      { role: 'P.R.O.', name: 'Jericho C. Ponce', shortName: 'Jericho Ponce' },
      { role: 'Sgt. at Arms', name: 'Antonio P. Agustin Jr.', shortName: 'Antonio Agustin' }
    ],
    students: [
      { name: 'Antonio P. Agustin Jr.', image: 'students/antonio-agustin.webp' },
      { name: 'Herman C. Aliangan Jr.', image: 'students/herman-aliangan.webp' },
      { name: 'Gilbert B. Anos', image: 'students/gilbert-anos.webp' },
      { name: 'Roy T. Benavides', image: 'students/roy-benavides.webp' },
      { name: 'Raymond P. Borcena', image: 'students/raymond-borcena.webp' },
      { name: 'Darmindar S. Brar', image: 'students/darmindar-brar.webp' },
      { name: 'Romeo N. Bucala', image: 'students/romeo-bucala.webp' },
      { name: 'Alfredo V. Camacho Jr.', image: 'students/alfredo-camacho.webp' },
      { name: 'John B. Candoleta', image: 'students/john-candoleta.webp' },
      { name: 'James Walter P. Capili', image: 'students/james-capili.webp' },
      { name: 'Jojo Rex Casaje', image: 'students/jojo-casaje.webp' },
      { name: 'Martin Omar J. Concepcion', image: 'students/martin-concepcion.webp' },
      { name: 'Fernando O. Cosme', image: 'students/fernando-cosme.webp' },
      { name: 'Remlee M. Dela Cruz', image: 'students/remlee-delacruz.webp' },
      { name: 'Romeo S. Diaz Jr.', image: 'students/romeo-diaz.webp' },
      { name: 'Romel C. Dinglasan', image: 'students/romel-dinglasan.webp' },
      { name: 'Rolando B. Duculan Jr.', image: 'students/rolando-duculan.webp' },
      { name: 'Ricardo M. Encarnacion', image: 'students/ricardo-encarnacion.webp' },
      { name: 'Leandro Edizer R. Enoval', image: 'students/leandro-enoval.webp' },
      { name: 'Philipp E. Erestain', image: 'students/philipp-erestain.webp' },
      { name: 'Aldrin George E. Floro', image: 'students/aldrin-floro.webp' },
      { name: 'Marvin T. Frondoso', image: 'students/marvin-frondoso.webp' },
      { name: 'Frederick F. Garcia', image: 'students/frederick-garcia.webp' },
      { name: 'Jason M. Gonzales', image: 'students/jason-gonzales.webp' },
      { name: 'Lemuel R. De Guzman', image: 'students/lemuel-deguzman.webp' },
      { name: 'Heartzell Jim B. Jardio', image: 'students/heartzell-jardio.webp' },
      { name: 'Farley John M. Javier', image: 'students/farley-javier.webp' },
      { name: 'Jose Angelito L. Leal', image: 'students/jose-leal.webp' },
      { name: 'Roberto C. Leonardo', image: 'students/roberto-leonardo.webp' },
      { name: 'Noriel Rayond C. Lim', image: 'students/noriel-lim.webp' },
      { name: 'Eduardo Z. Lucero Jr.', image: 'students/eduardo-lucero.webp' },
      { name: 'Erwin S. Marquez', image: 'students/erwin-marquez.webp' },
      { name: 'Nilo U. Martinez II', image: 'students/nilo-martinez.webp' },
      { name: 'John Joseph A. Morales', image: 'students/john-morales.webp' },
      { name: 'Edwin M. Natividad', image: 'students/edwin-natividad.webp' },
      { name: 'Michael A. Olesco', image: 'students/michael-olesco.webp' },
      { name: 'Vincent B. Olfindo', image: 'students/vincent-olfindo.webp' },
      { name: 'Edwin R. De Pacina', image: 'students/edwin-depacina.webp' },
      { name: 'Paul Eric S. Padilla', image: 'students/paul-padilla.webp' },
      { name: 'Edwin G. Paras', image: 'students/edwin-paras.webp' },
      { name: 'Paul D. Perez', image: 'students/paul-perez.webp' },
      { name: 'Jericho C. Ponce', image: 'students/jericho-ponce.webp' },
      { name: 'Arnold G. Rodriguez', image: 'students/arnold-rodriguez.webp' },
      { name: 'Ronald R. Sanchez', image: 'students/ronald-sanchez.webp' },
      { name: 'Roderick C. Santiago', image: 'students/roderick-santiago.webp' },
      { name: 'Rafael Santos', image: 'students/rafael-santos.webp' },
      { name: 'Mariano L. Serrano III', image: 'students/mariano-serrano.webp' },
      { name: 'Ruel Y. Sibal', image: 'students/ruel-sibal.webp' },
      { name: 'Juno Antonio A. Taco Jr.', image: 'students/juno-taco.webp' },
      { name: 'Rogelio B. Tapang', image: 'students/rogelio-tapang.webp' },
      { name: 'Eric B. Tee', image: 'students/eric-tee.webp' },
      { name: 'Jojo M. Uy', image: 'students/jojo-uy.webp' },
      { name: 'Joel Velasco', image: 'students/joel-velasco.webp' },
      { name: 'Romeo T. Vendivil', image: 'students/romeo-vendivil.webp' },
      { name: 'Von Ferdinand O. Villagarcia', image: 'students/von-villagarcia.webp' }
    ],
    other: [
    ]
  },
  {
    id: '424G',
    title: '424-G',
    adviser: { name: 'Ms. Glicelda Berja', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Erlinda V. Alvarez II', shortName: 'Erlinda Alvarez II' },
      { role: 'Vice-President', name: 'Anabel I. Mangali', shortName: 'Anabel Mangali' },
      { role: 'Secretary', name: 'Anna Lisa M. Belen', shortName: 'Anna Lisa Belen' },
      { role: 'Treasurer', name: 'Ma. Lani V. Reyes', shortName: 'Lani Reyes' },
      { role: 'P.R.O.', name: 'Marietta C. Vicencio', shortName: 'Marietta Vicencio' },
      { role: 'Sgt. at Arms', name: 'Cristina A. Parulan', shortName: 'Cristina Parulan' }
    ],
    students: [
      { name: 'Mary Jane C. Abad', image: 'students/mary-abad.webp' },
      { name: 'Erlinda V. Alvarez II', image: 'students/erlinda-alvarez.webp' },
      { name: 'Michelle C. Basiloy', image: 'students/michelle-basiloy.webp' },
      { name: 'Anna Lisa M. Belen', image: 'students/anna-belen.webp' },
      { name: 'Ma. Teresa S. Bulatao', image: 'students/teresa-bulatao.webp' },
      { name: 'Jeremiah I. Castaneda', image: 'students/jeremiah-castaneda.webp' },
      { name: 'Hazel B. Centeno', image: 'students/hazel-centeno.webp' },
      { name: 'Arlinda J. Cesa', image: 'students/arlinda-cesa.webp' },
      { name: 'Ma. Esperanza P. Dajoyag', image: 'students/esperanza-dajoyag.webp' },
      { name: 'Sheryll Mae M. Dandan', image: 'students/sheryll-dandan.webp' },
      { name: 'Catherine M. Dilig', image: 'students/catherine-dilig.webp' },
      { name: 'Myra F. Enriquez', image: 'students/myra-enriquez.webp' },
      { name: 'Jossie P. Escalante', image: 'students/jossie-escalante.webp' },
      { name: 'Joahnna P. Esguerra', image: 'students/joahnna-esguerra.webp' },
      { name: 'Gloria O. Esperanza', image: 'students/gloria-esperanza.webp' },
      { name: 'Aurita B. Gabay', image: 'students/aurita-gabay.webp' },
      { name: 'Deanna G. Guirnalda', image: 'students/deanna-guirnalda.webp' },
      { name: 'Angelica R. Guy', image: 'students/angelica-guy.webp' },
      { name: 'Jennifer C.Llano', image: 'students/jennifer-llano.webp' },
      { name: 'Ruby Joj M. Lacorte', image: 'students/ruby-lacorte.webp' },
      { name: 'Mary Claire L. Lacuesta', image: 'students/mary-lacuesta.webp' },
      { name: 'Maria Clara B. Lasa', image: 'students/maria-lasa.webp' },
      { name: 'Maria Mai Monica C. Ledesma', image: 'students/maria-ledesma.webp' },
      { name: 'Ma. Cristina B. Malijan', image: 'students/cristina-malijan.webp' },
      { name: 'Catherine M. Maliwanag', image: 'students/catherine-maliwanag.webp' },
      { name: 'Irene R. Mamaril', image: 'students/irene-mamaril.webp' },
      { name: 'Lourdes Marie D. Mandap', image: 'students/lourdes-mandap.webp' },
      { name: 'Anabel I. Mangali', image: 'students/anabel-mangali.webp' },
      { name: 'Mary Grace A. Mendiola', image: 'students/mary-mendiola.webp' },
      { name: 'Lily Ann S. Mina', image: 'students/lily-mina.webp' },
      { name: 'Ma. Carolyn M. Nera', image: 'students/carolyn-nera.webp' },
      { name: 'Cristina A. Parulan', image: 'students/cristina-parulan.webp' },
      { name: 'Catherine P. Pascua', image: 'students/catherine-pascua.webp' },
      { name: 'Alodie L. Penarubia', image: 'students/alodie-penarubia.webp' },
      { name: 'Ma. Lina D. Perpetua', image: 'students/lina-perpetua.webp' },
      { name: 'Karen L. Pitarde', image: 'students/karen-pitarde.webp' },
      { name: 'Floren R. Ragunton', image: 'students/floren-ragunton.webp' },
      { name: 'Lourdes C. Rasalan', image: 'students/lourdes-rasalan.webp' },
      { name: 'Arlene N. Reside', image: 'students/arlene-reside.webp' },
      { name: 'Ma. Lani V. Reyes', image: 'students/lani-reyes.webp' },
      { name: 'Rica Maria Antonette Z. Reyes', image: 'students/rica-reyes.webp' },
      { name: 'Marie Claire B. Romero', image: 'students/marie-romero.webp' },
      { name: 'Catherine M. Santos', image: 'students/catherine-santos.webp' },
      { name: 'Jennifer M. Santos', image: 'students/jennifer-santos.webp' },
      { name: 'Verna L. Santos', image: 'students/verna-santos.webp' },
      { name: 'Ma. Cristina R. Soriano', image: 'students/cristina-soriano.webp' },
      { name: 'Maymarie F. Sumera', image: 'students/maymarie-sumera.webp' },
      { name: 'Ma. Eloisa M. Tapang', image: 'students/eloisa-tapang.webp' },
      { name: 'Grace Patricia A. Tayag', image: 'students/grace-tayag.webp' },
      { name: 'Mary Rose G. Uy', image: 'students/mary-uy.webp' },
      { name: 'Marietta C. Vicencio', image: 'students/marietta-vicencio.webp' },
      { name: 'Mary Jane Villarica', image: 'students/mary-villarica.webp' },
      { name: 'Marjorie U. Villacruz', image: 'students/marjorie-villacruz.webp' },
      { name: 'Michelle Marie C. Vinzons', image: 'students/michelle-vinzons.webp' },
      { name: 'Ma. Isabel Loreto R. Zuela', image: 'students/isabel-zuela.webp' }
    ],
    other: [
    ]
  },
  {
    id: '424BG',
    title: '424-BG',
    adviser: { name: 'Mr. Danilo Concepcion', image: 'adviser.webp' },
    cover: { classPhoto: 'class-photo.webp' },
    officers: [
      { role: 'President', name: 'Myra C. Laforteza', shortName: 'Myra Laforteza' },
      { role: 'Vice-President', name: 'Michael P. Mutuc', shortName: 'Michael Mutuc' },
      { role: 'Secretary', name: 'Salmer P. Espinosa', shortName: 'Salmer Espinosa' },
      { role: 'Treasurer', name: 'Mary Gretchen Martinez', shortName: 'Gretchen Martinez' },
      { role: 'P.R.O.', name: 'Michelle Macapagal', shortName: 'Michelle Macapagal' },
      { role: 'Sgt. at Arms', name: 'Ramil B. Tuason', shortName: 'Ramil Tuason' }
    ],
    students: [
      { name: 'Alexandrius A. Alba', image: 'students/alexandrius-alba.webp' },
      { name: 'Rommel L. Alcantara', image: 'students/rommel-alcantara.webp' },
      { name: 'Jeffrey C. Dollente', image: 'students/jeffrey-dollente.webp' },
      { name: 'Tegie F. Dorado', image: 'students/tegie-dorado.webp' },
      { name: 'Salmer P. Espinosa', image: 'students/salmer-espinosa.webp' },
      { name: 'Ysmael F. Fernandez', image: 'students/ysmael-fernandez.webp' },
      { name: 'Gerardo S. Halili', image: 'students/gerardo-halili.webp' },
      { name: 'Joselito Q. De Leon', image: 'students/joselito-deleon.webp' },
      { name: 'Mar August B. Leoncio', image: 'students/mar-leoncio.webp' },
      { name: 'Angelo E. Llorando', image: 'students/angelo-llorando.webp' },
      { name: 'Edwin S. Manalastas', image: 'students/edwin-manalastas.webp' },
      { name: 'Bernardino C. Masilungan', image: 'students/bernardino-masilungan.webp' },
      { name: 'Julius Rendell L. Merencillo', image: 'students/julius-merencillo.webp' },
      { name: 'Brendan D. Morfe', image: 'students/brendan-morfe.webp' },
      { name: 'Michael P. Mutuc', image: 'students/michael-mutuc.webp' },
      { name: 'Edmon M. Naniong', image: 'students/edmon-naniong.webp' },
      { name: 'Arnulfo L. Necio', image: 'students/arnulfo-necio.webp' },
      { name: 'Antonio B. Pablo Jr.', image: 'students/antonio-pablo.webp' },
      { name: 'Jonathan Palanca', image: 'students/jonathan-palanca.webp' },
      { name: 'Alvin M. Pangilinan', image: 'students/alvin-pangilinan.webp' },
      { name: 'Salvador M. Peralta Jr.', image: 'students/salvador-peralta.webp' },
      { name: 'Eric D. J. Picar', image: 'students/eric-picar.webp' },
      { name: 'Norberto L. Punsalan', image: 'students/norberto-punsalan.webp' },
      { name: 'Jose Roderick T. Quintos', image: 'students/jose-quintos.webp' },
      { name: 'Peter T. Ramos', image: 'students/peter-ramos.webp' },
      { name: 'Addison C. Raymundo', image: 'students/addison-raymundo.webp' },
      { name: 'Adrian L. Reyes', image: 'students/adrian-reyes.webp' },
      { name: 'Leodegario C. De Los Reyes', image: 'students/leodegario-delosreyes.webp' },
      { name: 'Joseph Roy L. Sales', image: 'students/joseph-sales.webp' },
      { name: 'John Alross N. Salvosa', image: 'students/john-salvosa.webp' },
      { name: 'Frederick C. Solis', image: 'students/frederick-solis.webp' },
      { name: 'Leandro Albino B. Tibia', image: 'students/leandro-tibia.webp' },
      { name: 'Rolando D. Tolentino', image: 'students/rolando-tolentino.webp' },
      { name: 'Virgilio L. Tolentino', image: 'students/virgilio-tolentino.webp' },
      { name: 'Ramil B. Tuason', image: 'students/ramil-tuason.webp' },
      { name: 'Jose Antonio Y. Villar', image: 'students/jose-villar.webp' },
      { name: 'Jackson V. Yabut', image: 'students/jackson-yabut.webp' },
      { name: 'Ma. Imaculada T. Jovellanos', image: 'students/imaculada-jovellanos.webp' },
      { name: 'Lorna U. Lacsamana', image: 'students/lorna-lacsamana.webp' },
      { name: 'Myra C. Laforteza', image: 'students/myra-laforteza.webp' },
      { name: 'Ma. Theresa L. Largoza', image: 'students/theresa-largoza.webp' },
      { name: 'Rosemarie Fe A. De Leon', image: 'students/rosemarie-deleon.webp' },
      { name: 'Michelle Macapagal', image: 'students/michelle-macapagal.webp' },
      { name: 'Mary Gretchen Martinez', image: 'students/mary-martinez.webp' },
      { name: 'Catherine R. Miranda', image: 'students/catherine-miranda.webp' },
      { name: 'Jovie Anne Munar', image: 'students/jovie-munar.webp' },
      { name: 'Alma R. Pantaleon', image: 'students/alma-pantaleon.webp' },
      { name: 'Mylene C. Dela Pena', image: 'students/mylene-delapena.webp' },
      { name: 'Annalizza A. Reynon', image: 'students/annalizza-reynon.webp' },
      { name: 'Rhodora D. L. Roque', image: 'students/rhodora-roque.webp' },
      { name: 'Rowena P. Del Rosario', image: 'students/rowena-delrosario.webp' },
      { name: 'Maria Roselle E. Salac', image: 'students/maria-salac.webp' },
      { name: 'Linette R. Salvador', image: 'students/linette-salvador.webp' },
      { name: 'Daisylene M. Santos', image: 'students/daisylene-santos.webp' }
    ],
    other: [
        { title: 'Boys and girls!', image: 'other/classroom.webp' },
    ]
  }        
];
