export interface Officer {
  role: string;
  name: string;
  shortName: string;
}

export interface Student {
  name: string;
  image: string;
}

export interface OtherPhoto {
  title: string;
  image: string;
}

export interface SectionData {
  id: string;
  title: string;
  adviser: {
    name: string;
    image: string;
  };
  cover: {
    classPhoto: string;
  };
  officers: Officer[];
  students: Student[];
  other: OtherPhoto[];
}

export const sections: SectionData[] = [
  {
    id: '421G',
    title: '421-G',
    adviser: { name: 'Mrs. Norina Gapasin', image: 'adviser.jpg' },
    cover: { classPhoto: 'class-photo.jpg' },
    officers: [
      { role: 'President', name: 'Angie M. Arguna', shortName: 'Angie Arguna' },
      { role: 'Vice-President', name: 'Ma. Cecilia A. Nalagan', shortName: 'Cecilia Nalagan' },
      { role: 'Secretary', name: 'Marie Charlyn O. Exaltado', shortName: 'Marie Charlyn Exaltado' },
      { role: 'Treasurer', name: 'Vivian S. De Guzman', shortName: 'Vivian De Guzman' },
      { role: 'P.R.O.', name: 'Gladys R. Guitan', shortName: 'Gladys Guitan' },
      { role: 'Sgt. at Arms', name: 'Heidi S. Palaca', shortName: 'Heidi Palaca' }
    ],
    students: [
      { name: 'Grace Ann O. Alano', image: 'students/grace-alano.jpg' },
      { name: 'Noemi Ruth G. Aldez', image: 'students/noemi-aldez.jpg' },
      { name: 'Andrea Gladys Paz P. Aquino', image: 'students/andrea-aquino.jpg' },
      { name: 'Angie M. Arguna', image: 'students/angie-arguna.jpg' },
      { name: 'Leilani D. Aspeli', image: 'students/leilani-aspeli.jpg' },
      { name: 'Myrna F. Atienza', image: 'students/myrna-atienza.jpg' },
      { name: 'Elayda Clara Marie T. Beltran', image: 'students/elayda-beltran.jpg' },
      { name: 'Florence F. Buerano', image: 'students/florence-buerano.jpg' },
      { name: 'Carmela O. Castro', image: 'students/carmela-castro.jpg' },
      { name: 'Shirin Marie N. Elio', image: 'students/shirin-elio.jpg' },
      { name: 'Ma. Teresita M. Esguerra', image: 'students/teresita-esguerra.jpg' },
      { name: 'Cecile N. Espocia', image: 'students/cecile-espocia.jpg' },
      { name: 'Marie Charlyn O. Exaltado', image: 'students/marie-exaltado.jpg' },
      { name: 'Ressie R. Framil', image: 'students/ressie-framil.jpg' },
      { name: 'Vilma T. Gatchalian', image: 'students/vilma-gatchalian.jpg' },
      { name: 'Gladys R. Guitan', image: 'students/gladys-guitan.jpg' },
      { name: 'Vivian S. De Guzman', image: 'students/vivian-deguzman.jpg' },
      { name: 'Ma. Larissa M. Halili', image: 'students/larissa-halili.jpg' },
      { name: 'Ma. Cecilia V. Interior', image: 'students/cecilia-interior.jpg' },
      { name: 'Ma. Rosario I. Jimenez', image: 'students/rosario-jimenez.jpg' },
      { name: 'Katherine T. Justiniano', image: 'students/katherine-justiniano.jpg' },
      { name: 'Jolianne Q. Lan', image: 'students/jolianne-lan.jpg' },
      { name: 'Candice Twinkle S. Laureta', image: 'students/candice-laureta.jpg' },
      { name: 'Josephine P. Linsangan', image: 'students/josephine-linsangan.jpg' },
      { name: 'Ma. Viviane P. Magno', image: 'students/viviane-magno.jpg' },
      { name: 'Noemi B. Misicampo Jra.', image: 'students/noemi-misicampo.jpg' },
      { name: 'Regina Ma. Auxiliadora Mendigoria', image: 'students/regina-mendigoria.jpg' },
      { name: 'Naomi G. Milay', image: 'students/naomi-milay.jpg' },
      { name: 'Ma. Cecilia A. Nalagan', image: 'students/cecilia-nalagan.jpg' },
      { name: 'Ezelyn L. Navarro', image: 'students/ezelyn-navarro.jpg' },
      { name: 'Rosalinda G. Ong', image: 'students/rosalinda-ong.jpg' },
      { name: 'Ma. Alicia F. Paggabao', image: 'students/alicia-paggabao.jpg' },
      { name: 'Heidi S. Palaca', image: 'students/heidi-palaca.jpg' },
      { name: 'Connie H. Paris', image: 'students/connie-paris.jpg' },
      { name: 'Rowena V. Perez', image: 'students/rowena-perez.jpg' },
      { name: 'Mary Ann M. Quilala', image: 'students/maryann-quilala.jpg' },
      { name: 'Ma. Pacita B. Rivera', image: 'students/pacita-rivera.jpg' },
      { name: 'Nancy Grace A. Robles', image: 'students/nancy-robles.jpg' },
      { name: 'Violeta A. San Juan', image: 'students/violeta-sanjuan.jpg' },
      { name: 'Ma. Cristina F. Santos', image: 'students/cristina-santos.jpg' },
      { name: 'Aimee B. Sarmiento', image: 'students/aimee-sarmiento.jpg' },
      { name: 'Ma. Cecilia M. Soller', image: 'students/cecilia-soller.jpg' },
      { name: 'Kathrina V. Suarez', image: 'students/kathrina-suarez.jpg' },
      { name: 'Mitus L. Sumcad', image: 'students/mitus-sumcad.jpg' },
      { name: 'Ma. Virginia G. Tigno', image: 'students/virginia-tigno.jpg' },
      { name: 'Shirley G. Tismo', image: 'students/shirley-tismo.jpg' },
      { name: 'Rachel M. Tolosa', image: 'students/rachel-tolosa.jpg' },
      { name: 'Purificacion N. Tongol', image: 'students/purificacion-tongol.jpg' },
      { name: 'Veronica C. Umali', image: 'students/veronica-umali.jpg' },
      { name: 'Marites B. Uy', image: 'students/marites-uy.jpg' },
      { name: 'Mariechit Gloria S. De Vera', image: 'students/mariechit-devera.jpg' },
      { name: 'Marilou S. De Vera', image: 'students/marilou-devera.jpg' },
      { name: 'Shirley C. Yu', image: 'students/shirley-yu.jpg' }
    ],
    other: [
      { title: 'Mga pa-cute', image: 'other/classroom.jpg' },
    ]
  },
  {
    id: '421B',
    title: '421-B',
    adviser: { name: 'Mrs. Cipriana V. Yu', image: 'adviser.jpg' },
    cover: { classPhoto: 'class-photo.jpg' },
    officers: [
      { role: 'President', name: 'John Ulysses D. Abu', shortName: 'John Abu' },
      { role: 'Vice-President', name: 'Lyndon B. Denia', shortName: 'Lyndon Denia' },
      { role: 'Secretary', name: 'Ferdinand C. Bundang', shortName: 'Ferdinand Bundang' },
      { role: 'Treasurer', name: 'Augusto B. Cruz Jr.', shortName: 'Augusto Cruz Jr.' },
      { role: 'P.R.O.', name: 'Reynaldo C. Idano', shortName: 'Reynaldo Idano' },
      { role: 'Sgt. at Arms', name: 'Neil C. Tan', shortName: 'Neil Tan' }
    ],
    students: [
      { name: 'John Ulysses D. Abu', image: 'students/john-abu.jpg' },
      { name: 'Edgardo A. Agbada', image: 'students/edgardo-agbada.jpg' },
      { name: 'Jose Ma. G. Alarilla', image: 'students/jose-alarilla.jpg' },
      { name: 'Enrique G. Armentia', image: 'students/enrique-armentia.jpg' },
      { name: 'William A. Asuncion Jr.', image: 'students/william-asuncion.jpg' },
      { name: 'Raymond P. Azul', image: 'students/raymond-azul.jpg' },
      { name: 'Robert B. Belleza', image: 'students/robert-belleza.jpg' },
      { name: 'Gary Stephen S. Briones', image: 'students/gary-briones.jpg' },
      { name: 'Ruben F. Bukas Jr.', image: 'students/ruben-bukas.jpg' },
      { name: 'Ferdinand C. Bundang', image: 'students/ferdinand-bundang.jpg' },
      { name: 'Reynaldo C. Caladiao', image: 'students/reynaldo-caladiao.jpg' },
      { name: 'Ariel C. de Castro', image: 'students/ariel-decastro.jpg' },
      { name: 'Kenneth Lee G. de Castro', image: 'students/kenneth-decastro.jpg' },
      { name: 'Jeremy C. Chu', image: 'students/jeremy-chu.jpg' },
      { name: 'Renante C. Cortez', image: 'students/renante-cortez.jpg' },
      { name: 'Hector P. Crisostomo VI', image: 'students/hector-crisostomo.jpg' },
      { name: 'Augusto B. Cruz Jr.', image: 'students/augusto-cruz.jpg' },
      { name: 'Jesus Romano S. Datu', image: 'students/jesus-datu.jpg' },
      { name: 'Lyndon B. Denia', image: 'students/lyndon-denia.jpg' },
      { name: 'Ronald Reagan S. Domingo', image: 'students/ronald-domingo.jpg' },
      { name: 'John Kerwin G. Du', image: 'students/john-du.jpg' },
      { name: 'Henry D. Dumaoal', image: 'students/henry-dumaoal.jpg' },
      { name: 'Jericho G. Estrella', image: 'students/jericho-estrella.jpg' },
      { name: 'Dennis B. Hatoc', image: 'students/dennis-hatoc.jpg' },
      { name: 'Enrique R. Hipolito', image: 'students/enrique-hipolito.jpg' },
      { name: 'Reynaldo C. Idano', image: 'students/reynaldo-idano.jpg' },
      { name: 'Jonathan C. Javier', image: 'students/jonathan-javier.jpg' },
      { name: 'Ronald C. Jimenez', image: 'students/ronald-jimenez.jpg' },
      { name: 'Amor P. Lauro', image: 'students/amor-lauro.jpg' },
      { name: 'Paul Anthony P. Mandal', image: 'students/paul-mandal.jpg' },
      { name: 'Peter P. Mandal', image: 'students/peter-mandal.jpg' },
      { name: 'Ronaldo O. Marano', image: 'students/ronaldo-marano.jpg' },
      { name: 'John Paul T. Marbella', image: 'students/john-marbella.jpg' },
      { name: 'Ace Sterling R. Medina', image: 'students/ace-medina.jpg' },
      { name: 'Michael Conrad D. Mendoza', image: 'students/michael-mendoza.jpg' },
      { name: 'Julius Pichito T. Minas', image: 'students/julius-minas.jpg' },
      { name: 'Stephen Thomas S. Misa', image: 'students/stephen-misa.jpg' },
      { name: 'Renato K. Mitra Jr.', image: 'students/renato-mitra.jpg' },
      { name: 'Raymond I. Nano', image: 'students/raymond-nano.jpg' },
      { name: 'Jesus O. Ocasla', image: 'students/jesus-ocasla.jpg' },
      { name: 'Earl R. Perez', image: 'students/earl-perez.jpg' },
      { name: 'Maximino S. Picio III', image: 'students/maximino-picio.jpg' },
      { name: 'James S. Plaza', image: 'students/james-plaza.jpg' },
      { name: 'Rudyard Michael A. Ranjo', image: 'students/rudyard-ranjo.jpg' },
      { name: 'Gilbert G. Robles', image: 'students/gilbert-robles.jpg' },
      { name: 'Marianito R. Rodrigo', image: 'students/marianito-rodrigo.jpg' },
      { name: 'Dennis J. Rotairo', image: 'students/dennis-rotairo.jpg' },
      { name: 'Melanio G. Rubio Jr.', image: 'students/melanio-rubio.jpg' },
      { name: 'Neil C. Tan', image: 'students/neil-tan.jpg' },
      { name: 'Arnold B. Teodoro', image: 'students/arnold-teodoro.jpg' },
      { name: 'Randy G. Venezuela', image: 'students/randy-venezuela.jpg' },
      { name: 'Anthony Allan D. Villanueva', image: 'students/anthony-villanueva.jpg' },
      { name: 'Carlos C. Villarias Jr.', image: 'students/carlos-villarias.jpg' }
    ],
    other: [
      { title: 'Nerd paradise', image: 'other/classroom.jpg' }
    ]
  },
  {
    id: '422G',
    title: '422-G',
    adviser: { name: 'Mrs. Teresita N. Alves', image: 'adviser.jpg' },
    cover: { classPhoto: 'class-photo.jpg' },
    officers: [
      { role: 'President', name: 'Verna T. Miranda', shortName: 'Verna Miranda' },
      { role: 'Vice-President', name: 'Amillie Charito Jewel A. Japa', shortName: 'Amilie Japa' },
      { role: 'Secretary', name: 'Aileen C. Singson', shortName: 'Aileen Singson' },
      { role: 'Treasurer', name: 'Bernadette C. Lopez', shortName: 'Bernadette Lopez' },
      { role: 'P.R.O.', name: 'Brenda Joy O. Poblete', shortName: 'Brenda Poblete' },
      { role: 'Sgt. at Arms', name: 'Miriam O. Santos', shortName: 'Miriam Santos' }
    ],
    students: [
      { name: 'Evarose A. Alvarez', image: 'students/evarose-alvarez.jpg' },
      { name: 'Joan T. Apelo', image: 'students/joan-apelo.jpg' },
      { name: 'Rowena S. Baguino', image: 'students/rowena-baguino.jpg' },
      { name: 'Myra S. Batac', image: 'students/myra-batac.jpg' },
      { name: 'Ma. Lilibeth V. Batungbakal', image: 'students/lilibeth-batungbakal.jpg' },
      { name: 'Veronica L. Bautista', image: 'students/veronica-bautista.jpg' },
      { name: 'Vivienne D. Bautista', image: 'students/vivienne-bautista.jpg' },
      { name: 'Janette C. Benemerito', image: 'students/janette-benemerito.jpg' },
      { name: 'Angelica C. Bien', image: 'students/angelica-bien.jpg' },
      { name: 'Lizza E. Cabarles', image: 'students/lizza-cabarles.jpg' },
      { name: 'Anna Cielo Vic B. Canlas', image: 'students/anna-canlas.jpg' },
      { name: 'Ma. Theresa P. Carlos', image: 'students/theresa-carlos.jpg' },
      { name: 'Ma. Arlene S. Castillo', image: 'students/arlene-castillo.jpg' },
      { name: 'Mary Rose C. De Castro', image: 'students/mary-decastro.jpg' },
      { name: 'Sheila R. Castro', image: 'students/sheila-castro.jpg' },
      { name: 'Sonia J. Cordoviz', image: 'students/sonia-cordoviz.jpg' },
      { name: 'Aileen G. Cura', image: 'students/aileen-cura.jpg' },
      { name: 'Mary Grace A. Delgado', image: 'students/mary-delgado.jpg' },
      { name: 'Theresa Angela K. Dismas', image: 'students/theresa-dismas.jpg' },
      { name: 'Anna Bernardita M. Enriquez', image: 'students/anna-enriquez.jpg' },
      { name: 'Ma. Millicent C. Esberto', image: 'students/millicent-esberto.jpg' },
      { name: 'Romela F. Faeldonia', image: 'students/romela-faeldonia.jpg' },
      { name: 'Gina Maria C. Gener', image: 'students/gina-gener.jpg' },
      { name: 'Jocelyn S. Gapo', image: 'students/jocelyn-gapo.jpg' },
      { name: 'Fatima A. De Gorostiza', image: 'students/fatima-degorostiza.jpg' },
      { name: 'Ma. Joan Gualberto', image: 'students/joan-gualberto.jpg' },
      { name: 'Carmina Fatima V. De Guzman', image: 'students/carmina-deguzman.jpg' },
      { name: 'Amillie Charito Jewel A. Japa', image: 'students/amillie-japa.jpg' },
      { name: 'Myra Constancia B. Lachica', image: 'students/myra-lachica.jpg' },
      { name: 'Josephine C. Lampa', image: 'students/josephine-lampa.jpg' },
      { name: 'Bernadette C. Lopez', image: 'students/bernadette-lopez.jpg' },
      { name: 'Marilou J. Mendoza', image: 'students/marilou-mendoza.jpg' },
      { name: 'Jennifer C. Meneses', image: 'students/jennifer-meneses.jpg' },
      { name: 'Verna T. Miranda', image: 'students/verna-miranda.jpg' },
      { name: 'Janet C. Pineda', image: 'students/janet-pineda.jpg' },
      { name: 'Brenda Joy O. Poblete', image: 'students/brenda-poblete.jpg' },
      { name: 'Gloria D. Ramos', image: 'students/gloria-ramos.jpg' },
      { name: 'Anne Michelle P. Reyes', image: 'students/anne-reyes.jpg' },
      { name: 'Marisa P. De Los Reyes', image: 'students/marisa-delosreyes.jpg' },
      { name: 'Rosario C. Sandoval', image: 'students/rosario-sandoval.jpg' },
      { name: 'Ma. Cristina M. Santos', image: 'students/cristina-santos.jpg' },
      { name: 'Miriam O. Santos', image: 'students/miriam-santos.jpg' },
      { name: 'Ma. Nereza B. Santuyo', image: 'students/nereza-santuyo.jpg' },
      { name: 'Ma. Theresa S. Sena', image: 'students/theresa-sena.jpg' },
      { name: 'Aileen C. Singson', image: 'students/aileen-singson.jpg' },
      { name: 'Liza D. Solis', image: 'students/liza-solis.jpg' },
      { name: 'Anna Mae Tan', image: 'students/anna-tan.jpg' },
      { name: 'Maribeth A. Tan', image: 'students/maribeth-tan.jpg' },
      { name: 'Anita Flordeliza I. Tango', image: 'students/anita-tango.jpg' },
      { name: 'Lorelie B. Tiopes', image: 'students/lorelie-tiopes.jpg' },
      { name: 'Melinda B. Tolentino', image: 'students/melinda-tolentino.jpg' },
      { name: 'Mae Lahnee A. Unite', image: 'students/mae-unite.jpg' },
      { name: 'Ma. Jennifer N. Vidal', image: 'students/jennifer-vidal.jpg' },
      { name: 'Marie Abegail P. Villadolid', image: 'students/marie-villadolid.jpg' },
      { name: 'Ma. Jennifer S. Villanueva', image: 'students/jennifer-villanueva.jpg' }
    ],
    other: [      
    ]
  },
  {
    id: '422B',
    title: '422-B',
    adviser: { name: 'Ms. Teresita Y. Santos', image: 'adviser.jpg' },
    cover: { classPhoto: 'class-photo.jpg' },
    officers: [
      { role: 'President', name: 'Garrick Van V. Alumisin', shortName: 'Garrick Alumisin' },
      { role: 'Vice-President', name: 'Robert S. Jusay', shortName: 'Robert Jusay' },
      { role: 'Secretary', name: 'Gavini C. Pancho', shortName: 'Gavini Pancho' },
      { role: 'Treasurer', name: 'Roberto I. Belda', shortName: 'Roberto Belda' },
      { role: 'P.R.O.', name: 'Neil John V. Briones', shortName: 'Neil Briones' },
      { role: 'Sgt. at Arms', name: 'Cesar V. Dalde Jr.', shortName: 'Cesar Dalde' }
    ],
    students: [
      { name: 'Geoffrey F. Abello', image: 'students/geoffrey-abello.jpg' },
      { name: 'Marcelino J. Alejo Jr.', image: 'students/marcelino-alejo.jpg' },
      { name: 'Garrick Van V. Alumisin', image: 'students/garrick-alumisin.jpg' },
      { name: 'Bernabe Barr U. Ambrosio', image: 'students/bernabe-ambrosio.jpg' },
      { name: 'Gilbert C. Ang', image: 'students/gilbert-ang.jpg' },
      { name: 'Edwin I. Antonio', image: 'students/edwin-antonio.jpg' },
      { name: 'Rommel E. Argenal', image: 'students/rommel-argenal.jpg' },
      { name: 'Luisito D. Articulo', image: 'students/luisito-articulo.jpg' },
      { name: 'Zeus R. Balagtas', image: 'students/zeus-balagtas.jpg' },
      { name: 'Marlon R. Baltazar', image: 'students/marlon-baltazar.jpg' },
      { name: 'Ariel G. Bartilet', image: 'students/ariel-bartilet.jpg' },
      { name: 'Ramil D. Bataller', image: 'students/ramil-bataller.jpg' },
      { name: 'Roberto I. Belda', image: 'students/roberto-belda.jpg' },
      { name: 'Neil John V. Briones', image: 'students/neil-briones.jpg' },
      { name: 'Victor L. Cabochan', image: 'students/victor-cabochan.jpg' },
      { name: 'Paul John T. Camiring', image: 'students/paul-camiring.jpg' },
      { name: 'Leoberdo S. Cortez', image: 'students/leoberdo-cortez.jpg' },
      { name: 'Adonis P. Cruz', image: 'students/adonis-cruz.jpg' },
      { name: 'Cesar V. Dalde Jr.', image: 'students/cesar-dalde.jpg' },
      { name: 'Abraham B. Diaz', image: 'students/abraham-diaz.jpg' },
      { name: 'Danilo C. Eulogio', image: 'students/danilo-eulogio.jpg' },
      { name: 'Emmanuel C. Feliciano', image: 'students/emmanuel-feliciano.jpg' },
      { name: 'Manuel Erwin O. Felipe', image: 'students/manuel-felipe.jpg' },
      { name: 'Jaime Victor L. Gabriel', image: 'students/jaime-gabriel.jpg' },
      { name: 'Dominic E. Javier', image: 'students/dominic-javier.jpg' },
      { name: 'Robert Agustin A. De Jesus Jr.', image: 'students/robert-dejesus.jpg' },
      { name: 'Robert S. Jusay', image: 'students/robert-jusay.jpg' },
      { name: 'Alvin N. De Leon', image: 'students/alvin-deleon.jpg' },
      { name: 'Ramil M. Mirando', image: 'students/ramil-mirando.jpg' },
      { name: 'Sidney D. Munji', image: 'students/sidney-munji.jpg' },
      { name: 'Manuel M. Oliveros', image: 'students/manuel-oliveros.jpg' },
      { name: 'Dexter V. Pacheco', image: 'students/dexter-pacheco.jpg' },
      { name: 'Pancrasio D. Pahilan', image: 'students/pancrasio-pahilan.jpg' },
      { name: 'Alvin P. Palamos', image: 'students/alvin-palamos.jpg' },
      { name: 'Gavini C. Pancho', image: 'students/gavini-pancho.jpg' },
      { name: 'Andres Edgar R. Perez', image: 'students/andres-perez.jpg' },
      { name: 'Jose Angelo S. Petelo', image: 'students/jose-petelo.jpg' },
      { name: 'Miguel H. Podolig', image: 'students/miguel-podolig.jpg' },
      { name: 'Primo L. Prado', image: 'students/primo-prado.jpg' },
      { name: 'Michael Angelo A. Raymundo', image: 'students/michael-raymundo.jpg' },
      { name: 'Carlito M. Redaja', image: 'students/carlito-redaja.jpg' },
      { name: 'Roderick D. Reyes', image: 'students/roderick-reyes.jpg' },
      { name: 'Severino T. Salaguinto Jr.', image: 'students/severino-salaguinto.jpg' },
      { name: 'Hector Joseph E. Samson', image: 'students/hector-samson.jpg' },
      { name: 'Eric F. Santos', image: 'students/eric-santos.jpg' },
      { name: 'Menardo G. Soliven', image: 'students/menardo-soliven.jpg' },
      { name: 'Luisito G. Tirados', image: 'students/luisito-tirados.jpg' },
      { name: 'Alexander R. Torres Jr.', image: 'students/alexander-torres.jpg' },
      { name: 'Alexander D. Valmeo', image: 'students/alexander-valmeo.jpg' },
      { name: 'Rogelio Velicaria', image: 'students/rogelio-velicaria.jpg' },
      { name: 'Edgar R. Ventanilla', image: 'students/edgar-ventanilla.jpg' },
      { name: 'Reginaldo S. Villanueva', image: 'students/reginaldo-villanueva.jpg' },
      { name: 'Byron M. Villegas', image: 'students/byron-villegas.jpg' },
      { name: 'Florito L. Yalung', image: 'students/florito-yalung.jpg' },
      { name: 'Albert Q. Yamson III', image: 'students/albert-yamson.jpg' }
    ],
    other: []
  },
  {
    id: '423G',
    title: '423-G',
    adviser: { name: 'Mrs. Belinda N. Gallamos', image: 'adviser.jpg' },
    cover: { classPhoto: 'class-photo.jpg' },
    officers: [
      { role: 'President', name: 'Jocelyn C. Hechanova', shortName: 'Jocelyn Hechanova' },
      { role: 'Vice-President', name: 'Raquel N. Magistrado', shortName: 'Raquel Magistrado' },
      { role: 'Secretary', name: 'Maria Angelica M. Rena', shortName: 'Angelica Rena' },
      { role: 'Treasurer', name: 'Maria Joy V. Osea', shortName: 'Joy Osea' },
      { role: 'P.R.O.', name: 'Leila H. Palma', shortName: 'Leila Palma' },
      { role: 'Sgt. at Arms', name: 'Jonathan G. Baltazar', shortName: 'Jonathan Baltazar' }
    ],
    students: [
      { name: 'Maria Divina A. Alvarado', image: 'students/maria-alvarado.jpg' },
      { name: 'Carolina G. Artates', image: 'students/carolina-artates.jpg' },
      { name: 'Maria Angelita A. Baisa', image: 'students/maria-baisa.jpg' },
      { name: 'Jonathan G. Baltazar', image: 'students/jonathan-baltazar.jpg' },
      { name: 'Marissa C. Bautista', image: 'students/marissa-bautista.jpg' },
      { name: 'Melanie M. Bayro', image: 'students/melanie-bayro.jpg' },
      { name: 'Eliza F. Cabantig', image: 'students/eliza-cabantig.jpg' },
      { name: 'Elizabeth L. Caparas', image: 'students/elizabeth-caparas.jpg' },
      { name: 'Mitos R. Cayanan', image: 'students/mitos-cayanan.jpg' },
      { name: 'Miriam S. Concepcion', image: 'students/miriam-concepcion.jpg' },
      { name: 'Agnes M. Crelencia', image: 'students/agnes-crelencia.jpg' },
      { name: 'Criselda L. Cruz', image: 'students/criselda-cruz.jpg' },
      { name: 'Marinette Ann R. Cruz', image: 'students/marinette-cruz.jpg' },
      { name: 'Corinne Y. Cubias', image: 'students/corinne-cubias.jpg' },
      { name: 'Maria Vina S. Dinglasan', image: 'students/maria-dinglasan.jpg' },
      { name: 'Perla Florida L. Dirige', image: 'students/perla-dirige.jpg' },
      { name: 'Armida C. Estanislao', image: 'students/armida-estanislao.jpg' },
      { name: 'Mary Ann V. Esteban', image: 'students/mary-esteban.jpg' },
      { name: 'Jocelyn C. Hechanova', image: 'students/jocelyn-hechanova.jpg' },
      { name: 'Raquel N. Magistrado', image: 'students/raquel-magistrado.jpg' },
      { name: 'Nannette G. Manalese', image: 'students/nannette-manalese.jpg' },
      { name: 'Maria Josefina M. Manalo', image: 'students/maria-manalo.jpg' },
      { name: 'Elyn T. Mangrobang', image: 'students/elyn-mangrobang.jpg' },
      { name: 'Lyn Leni L. Mendoza', image: 'students/lyn-mendoza.jpg' },
      { name: 'Molly Ann S. Mendoza', image: 'students/molly-mendoza.jpg' },
      { name: 'Minabel Melchora B. Mercado', image: 'students/minabel-mercado.jpg' },
      { name: 'Cesarina B. Minas', image: 'students/cesarina-minas.jpg' },
      { name: 'Aileen B. Molina', image: 'students/aileen-molina.jpg' },
      { name: 'Annalyn G. Oliveros', image: 'students/annalyn-oliveros.jpg' },
      { name: 'Roby Ann Charmagne A. Opena', image: 'students/roby-opena.jpg' },
      { name: 'Yvonne M. Orlinda', image: 'students/yvonne-orlinda.jpg' },
      { name: 'Maria Joy V. Osea', image: 'students/maria-osea.jpg' },
      { name: 'Leila H. Palma', image: 'students/leila-palma.jpg' },
      { name: 'Grace B. Panganiban', image: 'students/grace-panganiban.jpg' },
      { name: 'Miriam V. Pangilinan', image: 'students/miriam-pangilinan.jpg' },
      { name: 'Alma T. Quitangon', image: 'students/alma-quitangon.jpg' },
      { name: 'Luisa Trinita S. Ranada', image: 'students/luisa-ranada.jpg' },
      { name: 'Maria Angelica M. Rena', image: 'students/maria-rena.jpg' },
      { name: 'Anna Lisa D. Rivera', image: 'students/anna-rivera.jpg' },
      { name: 'Christine P. Salando', image: 'students/christine-salando.jpg' },
      { name: 'Relynn F. Salanguit', image: 'students/relynn-salanguit.jpg' },
      { name: 'Mary Claire N. Serra', image: 'students/mary-serra.jpg' },
      { name: 'Maria Rosanna S. Sian', image: 'students/maria-sian.jpg' },
      { name: 'Jessica Ann M. Silo', image: 'students/jessica-silo.jpg' },
      { name: 'Arlene V. Sta. Ines', image: 'students/arlene-staines.jpg' },
      { name: 'Marie Phyllis E. Tablada', image: 'students/marie-tablada.jpg' },
      { name: 'Mary Beth A. Tan', image: 'students/mary-tan.jpg' },
      { name: 'Monica A. Tungol', image: 'students/monica-tungol.jpg' },
      { name: 'Lourdes M. Velasco', image: 'students/lourdes-velasco.jpg' },
      { name: 'Joanne Fabianne M. Viado', image: 'students/joanne-viado.jpg' },
      { name: 'Mary Ann I. Vuelba', image: 'students/mary-vuelba.jpg' },
      { name: 'Helen Grace A. Yanca', image: 'students/helen-yanca.jpg' },
      { name: 'Janet M. Yasona', image: 'students/janet-yasona.jpg' },
      { name: 'Leilanie P. Zaldarriaga', image: 'students/leilanie-zaldarriaga.jpg' }
    ],
    other: [      
      { title: 'Nice, sweet, and pretty', image: 'other/classroom.jpg' },
    ]
  },
  {
    id: '423B',
    title: '423-B',
    adviser: { name: 'Mr. Alexander Tagaro', image: 'adviser.jpg' },
    cover: { classPhoto: 'class-photo.jpg' },
    officers: [
      { role: 'President', name: 'Farley John M. Javier', shortName: 'Farley Javier' },
      { role: 'Vice-President', name: 'Remlee M. Dela Cruz', shortName: 'Remlee Dela Cruz' },
      { role: 'Secretary', name: 'Romeo S. Diaz Jr.', shortName: 'Romeo Diaz Jr.' },
      { role: 'Treasurer', name: 'Von Ferdinand O. Villagarcia', shortName: 'Von Villagarcia' },
      { role: 'P.R.O.', name: 'Jericho C. Ponce', shortName: 'Jericho Ponce' },
      { role: 'Sgt. at Arms', name: 'Antonio P. Agustin Jr.', shortName: 'Antonio Agustin' }
    ],
    students: [
      { name: 'Antonio P. Agustin Jr.', image: 'students/antonio-agustin.jpg' },
      { name: 'Herman C. Aliangan Jr.', image: 'students/herman-aliangan.jpg' },
      { name: 'Gilbert B. Anos', image: 'students/gilbert-anos.jpg' },
      { name: 'Roy T. Benavides', image: 'students/roy-benavides.jpg' },
      { name: 'Raymond P. Borcena', image: 'students/raymond-borcena.jpg' },
      { name: 'Darmindar S. Brar', image: 'students/darmindar-brar.jpg' },
      { name: 'Romeo N. Bucala', image: 'students/romeo-bucala.jpg' },
      { name: 'Alfredo V. Camacho Jr.', image: 'students/alfredo-camacho.jpg' },
      { name: 'John B. Candoleta', image: 'students/john-candoleta.jpg' },
      { name: 'James Walter P. Capili', image: 'students/james-capili.jpg' },
      { name: 'Jojo Rex Casaje', image: 'students/jojo-casaje.jpg' },
      { name: 'Martin Omar J. Concepcion', image: 'students/martin-concepcion.jpg' },
      { name: 'Fernando O. Cosme', image: 'students/fernando-cosme.jpg' },
      { name: 'Remlee M. Dela Cruz', image: 'students/remlee-delacruz.jpg' },
      { name: 'Romeo S. Diaz Jr.', image: 'students/romeo-diaz.jpg' },
      { name: 'Romel C. Dinglasan', image: 'students/romel-dinglasan.jpg' },
      { name: 'Rolando B. Duculan Jr.', image: 'students/rolando-duculan.jpg' },
      { name: 'Ricardo M. Encarnacion', image: 'students/ricardo-encarnacion.jpg' },
      { name: 'Leandro Edizer R. Enoval', image: 'students/leandro-enoval.jpg' },
      { name: 'Philipp E. Erestain', image: 'students/philipp-erestain.jpg' },
      { name: 'Aldrin George E. Floro', image: 'students/aldrin-floro.jpg' },
      { name: 'Marvin T. Frondoso', image: 'students/marvin-frondoso.jpg' },
      { name: 'Frederick F. Garcia', image: 'students/frederick-garcia.jpg' },
      { name: 'Jason M. Gonzales', image: 'students/jason-gonzales.jpg' },
      { name: 'Lemuel R. De Guzman', image: 'students/lemuel-deguzman.jpg' },
      { name: 'Heartzell Jim B. Jardio', image: 'students/heartzell-jardio.jpg' },
      { name: 'Farley John M. Javier', image: 'students/farley-javier.jpg' },
      { name: 'Jose Angelito L. Leal', image: 'students/jose-leal.jpg' },
      { name: 'Roberto C. Leonardo', image: 'students/roberto-leonardo.jpg' },
      { name: 'Noriel Rayond C. Lim', image: 'students/noriel-lim.jpg' },
      { name: 'Eduardo Z. Lucero Jr.', image: 'students/eduardo-lucero.jpg' },
      { name: 'Erwin S. Marquez', image: 'students/erwin-marquez.jpg' },
      { name: 'Nilo U. Martinez II', image: 'students/nilo-martinez.jpg' },
      { name: 'John Joseph A. Morales', image: 'students/john-morales.jpg' },
      { name: 'Edwin M. Natividad', image: 'students/edwin-natividad.jpg' },
      { name: 'Michael A. Olesco', image: 'students/michael-olesco.jpg' },
      { name: 'Vincent B. Olfindo', image: 'students/vincent-olfindo.jpg' },
      { name: 'Edwin R. De Pacina', image: 'students/edwin-depacina.jpg' },
      { name: 'Paul Eric S. Padilla', image: 'students/paul-padilla.jpg' },
      { name: 'Edwin G. Paras', image: 'students/edwin-paras.jpg' },
      { name: 'Paul D. Perez', image: 'students/paul-perez.jpg' },
      { name: 'Jericho C. Ponce', image: 'students/jericho-ponce.jpg' },
      { name: 'Arnold G. Rodriguez', image: 'students/arnold-rodriguez.jpg' },
      { name: 'Ronald R. Sanchez', image: 'students/ronald-sanchez.jpg' },
      { name: 'Roderick C. Santiago', image: 'students/roderick-santiago.jpg' },
      { name: 'Rafael Santos', image: 'students/rafael-santos.jpg' },
      { name: 'Mariano L. Serrano III', image: 'students/mariano-serrano.jpg' },
      { name: 'Ruel Y. Sibal', image: 'students/ruel-sibal.jpg' },
      { name: 'Juno Antonio A. Taco Jr.', image: 'students/juno-taco.jpg' },
      { name: 'Rogelio B. Tapang', image: 'students/rogelio-tapang.jpg' },
      { name: 'Eric B. Tee', image: 'students/eric-tee.jpg' },
      { name: 'Jojo M. Uy', image: 'students/jojo-uy.jpg' },
      { name: 'Joel Velasco', image: 'students/joel-velasco.jpg' },
      { name: 'Romeo T. Vendivil', image: 'students/romeo-vendivil.jpg' },
      { name: 'Von Ferdinand O. Villagarcia', image: 'students/von-villagarcia.jpg' }
    ],
    other: [
    ]
  }    
];
